// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/servicemanagement/v1/servicemanager.proto

package com.google.api.servicemanagement.v1;

public final class ServiceManagerProto {
  private ServiceManagerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServicesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServicesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_GetServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_GetServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_CreateServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_CreateServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_DeleteServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_DeleteServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_UndeleteServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_UndeleteServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_UndeleteServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_UndeleteServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServiceConfigsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServiceConfigsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_SubmitConfigSourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_SubmitConfigSourceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_CreateServiceRolloutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_CreateServiceRolloutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServiceRolloutsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_GetServiceRolloutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_GetServiceRolloutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_EnableServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_EnableServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_DisableServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_DisableServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_GenerateConfigReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_servicemanagement_v1_GenerateConfigReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4google/api/servicemanagement/v1/servic" +
      "emanager.proto\022\037google.api.servicemanage" +
      "ment.v1\032\034google/api/annotations.proto\032\030g" +
      "oogle/api/service.proto\032/google/api/serv" +
      "icemanagement/v1/resources.proto\032#google" +
      "/longrunning/operations.proto\032\031google/pr" +
      "otobuf/any.proto\032 google/protobuf/field_" +
      "mask.proto\032\034google/protobuf/struct.proto" +
      "\032\027google/rpc/status.proto\"n\n\023ListService" +
      "sRequest\022\033\n\023producer_project_id\030\001 \001(\t\022\021\n" +
      "\tpage_size\030\005 \001(\005\022\022\n\npage_token\030\006 \001(\t\022\023\n\013" +
      "consumer_id\030\007 \001(\t\"r\n\024ListServicesRespons" +
      "e\022A\n\010services\030\001 \003(\0132/.google.api.service" +
      "management.v1.ManagedService\022\027\n\017next_pag" +
      "e_token\030\002 \001(\t\")\n\021GetServiceRequest\022\024\n\014se" +
      "rvice_name\030\001 \001(\t\"X\n\024CreateServiceRequest" +
      "\022@\n\007service\030\001 \001(\0132/.google.api.servicema" +
      "nagement.v1.ManagedService\",\n\024DeleteServ" +
      "iceRequest\022\024\n\014service_name\030\001 \001(\t\".\n\026Unde" +
      "leteServiceRequest\022\024\n\014service_name\030\001 \001(\t" +
      "\"[\n\027UndeleteServiceResponse\022@\n\007service\030\001" +
      " \001(\0132/.google.api.servicemanagement.v1.M" +
      "anagedService\"\270\001\n\027GetServiceConfigReques" +
      "t\022\024\n\014service_name\030\001 \001(\t\022\021\n\tconfig_id\030\002 \001" +
      "(\t\022Q\n\004view\030\003 \001(\0162C.google.api.serviceman" +
      "agement.v1.GetServiceConfigRequest.Confi" +
      "gView\"!\n\nConfigView\022\t\n\005BASIC\020\000\022\010\n\004FULL\020\001" +
      "\"X\n\031ListServiceConfigsRequest\022\024\n\014service" +
      "_name\030\001 \001(\t\022\022\n\npage_token\030\002 \001(\t\022\021\n\tpage_" +
      "size\030\003 \001(\005\"c\n\032ListServiceConfigsResponse" +
      "\022,\n\017service_configs\030\001 \003(\0132\023.google.api.S" +
      "ervice\022\027\n\017next_page_token\030\002 \001(\t\"_\n\032Creat" +
      "eServiceConfigRequest\022\024\n\014service_name\030\001 " +
      "\001(\t\022+\n\016service_config\030\002 \001(\0132\023.google.api" +
      ".Service\"\216\001\n\031SubmitConfigSourceRequest\022\024" +
      "\n\014service_name\030\001 \001(\t\022D\n\rconfig_source\030\002 " +
      "\001(\0132-.google.api.servicemanagement.v1.Co" +
      "nfigSource\022\025\n\rvalidate_only\030\003 \001(\010\"I\n\032Sub" +
      "mitConfigSourceResponse\022+\n\016service_confi" +
      "g\030\001 \001(\0132\023.google.api.Service\"n\n\033CreateSe" +
      "rviceRolloutRequest\022\024\n\014service_name\030\001 \001(" +
      "\t\0229\n\007rollout\030\002 \001(\0132(.google.api.servicem" +
      "anagement.v1.Rollout\"i\n\032ListServiceRollo" +
      "utsRequest\022\024\n\014service_name\030\001 \001(\t\022\022\n\npage" +
      "_token\030\002 \001(\t\022\021\n\tpage_size\030\003 \001(\005\022\016\n\006filte" +
      "r\030\004 \001(\t\"r\n\033ListServiceRolloutsResponse\022:" +
      "\n\010rollouts\030\001 \003(\0132(.google.api.serviceman" +
      "agement.v1.Rollout\022\027\n\017next_page_token\030\002 " +
      "\001(\t\"D\n\030GetServiceRolloutRequest\022\024\n\014servi" +
      "ce_name\030\001 \001(\t\022\022\n\nrollout_id\030\002 \001(\t\"A\n\024Ena" +
      "bleServiceRequest\022\024\n\014service_name\030\001 \001(\t\022" +
      "\023\n\013consumer_id\030\002 \001(\t\"B\n\025DisableServiceRe" +
      "quest\022\024\n\014service_name\030\001 \001(\t\022\023\n\013consumer_" +
      "id\030\002 \001(\t\"q\n\033GenerateConfigReportRequest\022" +
      "(\n\nnew_config\030\001 \001(\0132\024.google.protobuf.An" +
      "y\022(\n\nold_config\030\002 \001(\0132\024.google.protobuf." +
      "Any\"\311\001\n\034GenerateConfigReportResponse\022\024\n\014" +
      "service_name\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022E\n\016change" +
      "_reports\030\003 \003(\0132-.google.api.servicemanag" +
      "ement.v1.ChangeReport\022@\n\013diagnostics\030\004 \003" +
      "(\0132+.google.api.servicemanagement.v1.Dia" +
      "gnostic2\324\023\n\016ServiceManager\022\221\001\n\014ListServi" +
      "ces\0224.google.api.servicemanagement.v1.Li" +
      "stServicesRequest\0325.google.api.servicema" +
      "nagement.v1.ListServicesResponse\"\024\202\323\344\223\002\016" +
      "\022\014/v1/services\022\226\001\n\nGetService\0222.google.a" +
      "pi.servicemanagement.v1.GetServiceReques" +
      "t\032/.google.api.servicemanagement.v1.Mana" +
      "gedService\"#\202\323\344\223\002\035\022\033/v1/services/{servic" +
      "e_name}\022\204\001\n\rCreateService\0225.google.api.s" +
      "ervicemanagement.v1.CreateServiceRequest" +
      "\032\035.google.longrunning.Operation\"\035\202\323\344\223\002\027\"" +
      "\014/v1/services:\007service\022\212\001\n\rDeleteService" +
      "\0225.google.api.servicemanagement.v1.Delet" +
      "eServiceRequest\032\035.google.longrunning.Ope" +
      "ration\"#\202\323\344\223\002\035*\033/v1/services/{service_na" +
      "me}\022\227\001\n\017UndeleteService\0227.google.api.ser" +
      "vicemanagement.v1.UndeleteServiceRequest" +
      "\032\035.google.longrunning.Operation\",\202\323\344\223\002&\"" +
      "$/v1/services/{service_name}:undelete\022\272\001" +
      "\n\022ListServiceConfigs\022:.google.api.servic" +
      "emanagement.v1.ListServiceConfigsRequest" +
      "\032;.google.api.servicemanagement.v1.ListS" +
      "erviceConfigsResponse\"+\202\323\344\223\002%\022#/v1/servi" +
      "ces/{service_name}/configs\022\300\001\n\020GetServic" +
      "eConfig\0228.google.api.servicemanagement.v" +
      "1.GetServiceConfigRequest\032\023.google.api.S" +
      "ervice\"]\202\323\344\223\002W\022//v1/services/{service_na" +
      "me}/configs/{config_id}Z$\022\"/v1/services/" +
      "{service_name}/config\022\244\001\n\023CreateServiceC" +
      "onfig\022;.google.api.servicemanagement.v1." +
      "CreateServiceConfigRequest\032\023.google.api." +
      "Service\";\202\323\344\223\0025\"#/v1/services/{service_n" +
      "ame}/configs:\016service_config\022\246\001\n\022SubmitC" +
      "onfigSource\022:.google.api.servicemanageme" +
      "nt.v1.SubmitConfigSourceRequest\032\035.google" +
      ".longrunning.Operation\"5\202\323\344\223\002/\"*/v1/serv" +
      "ices/{service_name}/configs:submit:\001*\022\276\001" +
      "\n\023ListServiceRollouts\022;.google.api.servi" +
      "cemanagement.v1.ListServiceRolloutsReque" +
      "st\032<.google.api.servicemanagement.v1.Lis" +
      "tServiceRolloutsResponse\",\202\323\344\223\002&\022$/v1/se" +
      "rvices/{service_name}/rollouts\022\263\001\n\021GetSe" +
      "rviceRollout\0229.google.api.servicemanagem" +
      "ent.v1.GetServiceRolloutRequest\032(.google" +
      ".api.servicemanagement.v1.Rollout\"9\202\323\344\223\002" +
      "3\0221/v1/services/{service_name}/rollouts/" +
      "{rollout_id}\022\252\001\n\024CreateServiceRollout\022<." +
      "google.api.servicemanagement.v1.CreateSe" +
      "rviceRolloutRequest\032\035.google.longrunning" +
      ".Operation\"5\202\323\344\223\002/\"$/v1/services/{servic" +
      "e_name}/rollouts:\007rollout\022\301\001\n\024GenerateCo" +
      "nfigReport\022<.google.api.servicemanagemen" +
      "t.v1.GenerateConfigReportRequest\032=.googl" +
      "e.api.servicemanagement.v1.GenerateConfi" +
      "gReportResponse\",\202\323\344\223\002&\"!/v1/services:ge" +
      "nerateConfigReport:\001*\022\224\001\n\rEnableService\022" +
      "5.google.api.servicemanagement.v1.Enable" +
      "ServiceRequest\032\035.google.longrunning.Oper" +
      "ation\"-\202\323\344\223\002\'\"\"/v1/services/{service_nam" +
      "e}:enable:\001*\022\227\001\n\016DisableService\0226.google" +
      ".api.servicemanagement.v1.DisableService" +
      "Request\032\035.google.longrunning.Operation\"." +
      "\202\323\344\223\002(\"#/v1/services/{service_name}:disa" +
      "ble:\001*B\335\001\n#com.google.api.servicemanagem" +
      "ent.v1B\023ServiceManagerProtoP\001ZPgoogle.go" +
      "lang.org/genproto/googleapis/api/service" +
      "management/v1;servicemanagement\242\002\004GASM\252\002" +
      "!Google.Cloud.ServiceManagement.V1\312\002!Goo" +
      "gle\\Cloud\\ServiceManagement\\V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ServiceProto.getDescriptor(),
          com.google.api.servicemanagement.v1.ResourcesProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        }, assigner);
    internal_static_google_api_servicemanagement_v1_ListServicesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_servicemanagement_v1_ListServicesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServicesRequest_descriptor,
        new java.lang.String[] { "ProducerProjectId", "PageSize", "PageToken", "ConsumerId", });
    internal_static_google_api_servicemanagement_v1_ListServicesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_api_servicemanagement_v1_ListServicesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServicesResponse_descriptor,
        new java.lang.String[] { "Services", "NextPageToken", });
    internal_static_google_api_servicemanagement_v1_GetServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_api_servicemanagement_v1_GetServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_GetServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", });
    internal_static_google_api_servicemanagement_v1_CreateServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_api_servicemanagement_v1_CreateServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_CreateServiceRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_google_api_servicemanagement_v1_DeleteServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_api_servicemanagement_v1_DeleteServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_DeleteServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", });
    internal_static_google_api_servicemanagement_v1_UndeleteServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_api_servicemanagement_v1_UndeleteServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_UndeleteServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", });
    internal_static_google_api_servicemanagement_v1_UndeleteServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_api_servicemanagement_v1_UndeleteServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_UndeleteServiceResponse_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_GetServiceConfigRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ConfigId", "View", });
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServiceConfigsRequest_descriptor,
        new java.lang.String[] { "ServiceName", "PageToken", "PageSize", });
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_api_servicemanagement_v1_ListServiceConfigsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServiceConfigsResponse_descriptor,
        new java.lang.String[] { "ServiceConfigs", "NextPageToken", });
    internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_CreateServiceConfigRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceConfig", });
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_SubmitConfigSourceRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ConfigSource", "ValidateOnly", });
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_api_servicemanagement_v1_SubmitConfigSourceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_SubmitConfigSourceResponse_descriptor,
        new java.lang.String[] { "ServiceConfig", });
    internal_static_google_api_servicemanagement_v1_CreateServiceRolloutRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_api_servicemanagement_v1_CreateServiceRolloutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_CreateServiceRolloutRequest_descriptor,
        new java.lang.String[] { "ServiceName", "Rollout", });
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServiceRolloutsRequest_descriptor,
        new java.lang.String[] { "ServiceName", "PageToken", "PageSize", "Filter", });
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_ListServiceRolloutsResponse_descriptor,
        new java.lang.String[] { "Rollouts", "NextPageToken", });
    internal_static_google_api_servicemanagement_v1_GetServiceRolloutRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_api_servicemanagement_v1_GetServiceRolloutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_GetServiceRolloutRequest_descriptor,
        new java.lang.String[] { "ServiceName", "RolloutId", });
    internal_static_google_api_servicemanagement_v1_EnableServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_api_servicemanagement_v1_EnableServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_EnableServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ConsumerId", });
    internal_static_google_api_servicemanagement_v1_DisableServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_api_servicemanagement_v1_DisableServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_DisableServiceRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ConsumerId", });
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_GenerateConfigReportRequest_descriptor,
        new java.lang.String[] { "NewConfig", "OldConfig", });
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_api_servicemanagement_v1_GenerateConfigReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_servicemanagement_v1_GenerateConfigReportResponse_descriptor,
        new java.lang.String[] { "ServiceName", "Id", "ChangeReports", "Diagnostics", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ServiceProto.getDescriptor();
    com.google.api.servicemanagement.v1.ResourcesProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
