// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1alpha1/conformance_service.proto

package com.google.api.expr.v1alpha1;

/**
 * <pre>
 * Request message for the Check method.
 * </pre>
 *
 * Protobuf type {@code google.api.expr.v1alpha1.CheckRequest}
 */
public  final class CheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.expr.v1alpha1.CheckRequest)
    CheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckRequest.newBuilder() to construct.
  private CheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckRequest() {
    typeEnv_ = java.util.Collections.emptyList();
    container_ = "";
    noStdEnv_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.api.expr.v1alpha1.ParsedExpr.Builder subBuilder = null;
            if (parsedExpr_ != null) {
              subBuilder = parsedExpr_.toBuilder();
            }
            parsedExpr_ = input.readMessage(com.google.api.expr.v1alpha1.ParsedExpr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(parsedExpr_);
              parsedExpr_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              typeEnv_ = new java.util.ArrayList<com.google.api.expr.v1alpha1.Decl>();
              mutable_bitField0_ |= 0x00000002;
            }
            typeEnv_.add(
                input.readMessage(com.google.api.expr.v1alpha1.Decl.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            container_ = s;
            break;
          }
          case 32: {

            noStdEnv_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        typeEnv_ = java.util.Collections.unmodifiableList(typeEnv_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_CheckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_CheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.api.expr.v1alpha1.CheckRequest.class, com.google.api.expr.v1alpha1.CheckRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PARSED_EXPR_FIELD_NUMBER = 1;
  private com.google.api.expr.v1alpha1.ParsedExpr parsedExpr_;
  /**
   * <pre>
   * Required. The parsed representation of the CEL program.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
   */
  public boolean hasParsedExpr() {
    return parsedExpr_ != null;
  }
  /**
   * <pre>
   * Required. The parsed representation of the CEL program.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
   */
  public com.google.api.expr.v1alpha1.ParsedExpr getParsedExpr() {
    return parsedExpr_ == null ? com.google.api.expr.v1alpha1.ParsedExpr.getDefaultInstance() : parsedExpr_;
  }
  /**
   * <pre>
   * Required. The parsed representation of the CEL program.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
   */
  public com.google.api.expr.v1alpha1.ParsedExprOrBuilder getParsedExprOrBuilder() {
    return getParsedExpr();
  }

  public static final int TYPE_ENV_FIELD_NUMBER = 2;
  private java.util.List<com.google.api.expr.v1alpha1.Decl> typeEnv_;
  /**
   * <pre>
   * Declarations of types for external variables and functions.
   * Required if program uses external variables or functions
   * not in the default environment.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
   */
  public java.util.List<com.google.api.expr.v1alpha1.Decl> getTypeEnvList() {
    return typeEnv_;
  }
  /**
   * <pre>
   * Declarations of types for external variables and functions.
   * Required if program uses external variables or functions
   * not in the default environment.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
   */
  public java.util.List<? extends com.google.api.expr.v1alpha1.DeclOrBuilder> 
      getTypeEnvOrBuilderList() {
    return typeEnv_;
  }
  /**
   * <pre>
   * Declarations of types for external variables and functions.
   * Required if program uses external variables or functions
   * not in the default environment.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
   */
  public int getTypeEnvCount() {
    return typeEnv_.size();
  }
  /**
   * <pre>
   * Declarations of types for external variables and functions.
   * Required if program uses external variables or functions
   * not in the default environment.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
   */
  public com.google.api.expr.v1alpha1.Decl getTypeEnv(int index) {
    return typeEnv_.get(index);
  }
  /**
   * <pre>
   * Declarations of types for external variables and functions.
   * Required if program uses external variables or functions
   * not in the default environment.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
   */
  public com.google.api.expr.v1alpha1.DeclOrBuilder getTypeEnvOrBuilder(
      int index) {
    return typeEnv_.get(index);
  }

  public static final int CONTAINER_FIELD_NUMBER = 3;
  private volatile java.lang.Object container_;
  /**
   * <pre>
   * The protocol buffer context.  See "Name Resolution" in the
   * Language Definition.
   * </pre>
   *
   * <code>string container = 3;</code>
   */
  public java.lang.String getContainer() {
    java.lang.Object ref = container_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      container_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The protocol buffer context.  See "Name Resolution" in the
   * Language Definition.
   * </pre>
   *
   * <code>string container = 3;</code>
   */
  public com.google.protobuf.ByteString
      getContainerBytes() {
    java.lang.Object ref = container_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      container_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NO_STD_ENV_FIELD_NUMBER = 4;
  private boolean noStdEnv_;
  /**
   * <pre>
   * If true, use only the declarations in
   * [type_env][google.api.expr.v1alpha1.CheckRequest.type_env].  If false
   * (default), add declarations for the standard definitions to the type
   * environment.  See "Standard Definitions" in the Language Definition.
   * </pre>
   *
   * <code>bool no_std_env = 4;</code>
   */
  public boolean getNoStdEnv() {
    return noStdEnv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (parsedExpr_ != null) {
      output.writeMessage(1, getParsedExpr());
    }
    for (int i = 0; i < typeEnv_.size(); i++) {
      output.writeMessage(2, typeEnv_.get(i));
    }
    if (!getContainerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, container_);
    }
    if (noStdEnv_ != false) {
      output.writeBool(4, noStdEnv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (parsedExpr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getParsedExpr());
    }
    for (int i = 0; i < typeEnv_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, typeEnv_.get(i));
    }
    if (!getContainerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, container_);
    }
    if (noStdEnv_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, noStdEnv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.api.expr.v1alpha1.CheckRequest)) {
      return super.equals(obj);
    }
    com.google.api.expr.v1alpha1.CheckRequest other = (com.google.api.expr.v1alpha1.CheckRequest) obj;

    boolean result = true;
    result = result && (hasParsedExpr() == other.hasParsedExpr());
    if (hasParsedExpr()) {
      result = result && getParsedExpr()
          .equals(other.getParsedExpr());
    }
    result = result && getTypeEnvList()
        .equals(other.getTypeEnvList());
    result = result && getContainer()
        .equals(other.getContainer());
    result = result && (getNoStdEnv()
        == other.getNoStdEnv());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasParsedExpr()) {
      hash = (37 * hash) + PARSED_EXPR_FIELD_NUMBER;
      hash = (53 * hash) + getParsedExpr().hashCode();
    }
    if (getTypeEnvCount() > 0) {
      hash = (37 * hash) + TYPE_ENV_FIELD_NUMBER;
      hash = (53 * hash) + getTypeEnvList().hashCode();
    }
    hash = (37 * hash) + CONTAINER_FIELD_NUMBER;
    hash = (53 * hash) + getContainer().hashCode();
    hash = (37 * hash) + NO_STD_ENV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoStdEnv());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.expr.v1alpha1.CheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for the Check method.
   * </pre>
   *
   * Protobuf type {@code google.api.expr.v1alpha1.CheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.expr.v1alpha1.CheckRequest)
      com.google.api.expr.v1alpha1.CheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_CheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_CheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.api.expr.v1alpha1.CheckRequest.class, com.google.api.expr.v1alpha1.CheckRequest.Builder.class);
    }

    // Construct using com.google.api.expr.v1alpha1.CheckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTypeEnvFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (parsedExprBuilder_ == null) {
        parsedExpr_ = null;
      } else {
        parsedExpr_ = null;
        parsedExprBuilder_ = null;
      }
      if (typeEnvBuilder_ == null) {
        typeEnv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        typeEnvBuilder_.clear();
      }
      container_ = "";

      noStdEnv_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_CheckRequest_descriptor;
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.CheckRequest getDefaultInstanceForType() {
      return com.google.api.expr.v1alpha1.CheckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.CheckRequest build() {
      com.google.api.expr.v1alpha1.CheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.CheckRequest buildPartial() {
      com.google.api.expr.v1alpha1.CheckRequest result = new com.google.api.expr.v1alpha1.CheckRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (parsedExprBuilder_ == null) {
        result.parsedExpr_ = parsedExpr_;
      } else {
        result.parsedExpr_ = parsedExprBuilder_.build();
      }
      if (typeEnvBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          typeEnv_ = java.util.Collections.unmodifiableList(typeEnv_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.typeEnv_ = typeEnv_;
      } else {
        result.typeEnv_ = typeEnvBuilder_.build();
      }
      result.container_ = container_;
      result.noStdEnv_ = noStdEnv_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.api.expr.v1alpha1.CheckRequest) {
        return mergeFrom((com.google.api.expr.v1alpha1.CheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.api.expr.v1alpha1.CheckRequest other) {
      if (other == com.google.api.expr.v1alpha1.CheckRequest.getDefaultInstance()) return this;
      if (other.hasParsedExpr()) {
        mergeParsedExpr(other.getParsedExpr());
      }
      if (typeEnvBuilder_ == null) {
        if (!other.typeEnv_.isEmpty()) {
          if (typeEnv_.isEmpty()) {
            typeEnv_ = other.typeEnv_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTypeEnvIsMutable();
            typeEnv_.addAll(other.typeEnv_);
          }
          onChanged();
        }
      } else {
        if (!other.typeEnv_.isEmpty()) {
          if (typeEnvBuilder_.isEmpty()) {
            typeEnvBuilder_.dispose();
            typeEnvBuilder_ = null;
            typeEnv_ = other.typeEnv_;
            bitField0_ = (bitField0_ & ~0x00000002);
            typeEnvBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTypeEnvFieldBuilder() : null;
          } else {
            typeEnvBuilder_.addAllMessages(other.typeEnv_);
          }
        }
      }
      if (!other.getContainer().isEmpty()) {
        container_ = other.container_;
        onChanged();
      }
      if (other.getNoStdEnv() != false) {
        setNoStdEnv(other.getNoStdEnv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.api.expr.v1alpha1.CheckRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.api.expr.v1alpha1.CheckRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.api.expr.v1alpha1.ParsedExpr parsedExpr_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.api.expr.v1alpha1.ParsedExpr, com.google.api.expr.v1alpha1.ParsedExpr.Builder, com.google.api.expr.v1alpha1.ParsedExprOrBuilder> parsedExprBuilder_;
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public boolean hasParsedExpr() {
      return parsedExprBuilder_ != null || parsedExpr_ != null;
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public com.google.api.expr.v1alpha1.ParsedExpr getParsedExpr() {
      if (parsedExprBuilder_ == null) {
        return parsedExpr_ == null ? com.google.api.expr.v1alpha1.ParsedExpr.getDefaultInstance() : parsedExpr_;
      } else {
        return parsedExprBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public Builder setParsedExpr(com.google.api.expr.v1alpha1.ParsedExpr value) {
      if (parsedExprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parsedExpr_ = value;
        onChanged();
      } else {
        parsedExprBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public Builder setParsedExpr(
        com.google.api.expr.v1alpha1.ParsedExpr.Builder builderForValue) {
      if (parsedExprBuilder_ == null) {
        parsedExpr_ = builderForValue.build();
        onChanged();
      } else {
        parsedExprBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public Builder mergeParsedExpr(com.google.api.expr.v1alpha1.ParsedExpr value) {
      if (parsedExprBuilder_ == null) {
        if (parsedExpr_ != null) {
          parsedExpr_ =
            com.google.api.expr.v1alpha1.ParsedExpr.newBuilder(parsedExpr_).mergeFrom(value).buildPartial();
        } else {
          parsedExpr_ = value;
        }
        onChanged();
      } else {
        parsedExprBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public Builder clearParsedExpr() {
      if (parsedExprBuilder_ == null) {
        parsedExpr_ = null;
        onChanged();
      } else {
        parsedExpr_ = null;
        parsedExprBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public com.google.api.expr.v1alpha1.ParsedExpr.Builder getParsedExprBuilder() {
      
      onChanged();
      return getParsedExprFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    public com.google.api.expr.v1alpha1.ParsedExprOrBuilder getParsedExprOrBuilder() {
      if (parsedExprBuilder_ != null) {
        return parsedExprBuilder_.getMessageOrBuilder();
      } else {
        return parsedExpr_ == null ?
            com.google.api.expr.v1alpha1.ParsedExpr.getDefaultInstance() : parsedExpr_;
      }
    }
    /**
     * <pre>
     * Required. The parsed representation of the CEL program.
     * </pre>
     *
     * <code>.google.api.expr.v1alpha1.ParsedExpr parsed_expr = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.api.expr.v1alpha1.ParsedExpr, com.google.api.expr.v1alpha1.ParsedExpr.Builder, com.google.api.expr.v1alpha1.ParsedExprOrBuilder> 
        getParsedExprFieldBuilder() {
      if (parsedExprBuilder_ == null) {
        parsedExprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.api.expr.v1alpha1.ParsedExpr, com.google.api.expr.v1alpha1.ParsedExpr.Builder, com.google.api.expr.v1alpha1.ParsedExprOrBuilder>(
                getParsedExpr(),
                getParentForChildren(),
                isClean());
        parsedExpr_ = null;
      }
      return parsedExprBuilder_;
    }

    private java.util.List<com.google.api.expr.v1alpha1.Decl> typeEnv_ =
      java.util.Collections.emptyList();
    private void ensureTypeEnvIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        typeEnv_ = new java.util.ArrayList<com.google.api.expr.v1alpha1.Decl>(typeEnv_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1alpha1.Decl, com.google.api.expr.v1alpha1.Decl.Builder, com.google.api.expr.v1alpha1.DeclOrBuilder> typeEnvBuilder_;

    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public java.util.List<com.google.api.expr.v1alpha1.Decl> getTypeEnvList() {
      if (typeEnvBuilder_ == null) {
        return java.util.Collections.unmodifiableList(typeEnv_);
      } else {
        return typeEnvBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public int getTypeEnvCount() {
      if (typeEnvBuilder_ == null) {
        return typeEnv_.size();
      } else {
        return typeEnvBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public com.google.api.expr.v1alpha1.Decl getTypeEnv(int index) {
      if (typeEnvBuilder_ == null) {
        return typeEnv_.get(index);
      } else {
        return typeEnvBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder setTypeEnv(
        int index, com.google.api.expr.v1alpha1.Decl value) {
      if (typeEnvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeEnvIsMutable();
        typeEnv_.set(index, value);
        onChanged();
      } else {
        typeEnvBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder setTypeEnv(
        int index, com.google.api.expr.v1alpha1.Decl.Builder builderForValue) {
      if (typeEnvBuilder_ == null) {
        ensureTypeEnvIsMutable();
        typeEnv_.set(index, builderForValue.build());
        onChanged();
      } else {
        typeEnvBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder addTypeEnv(com.google.api.expr.v1alpha1.Decl value) {
      if (typeEnvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeEnvIsMutable();
        typeEnv_.add(value);
        onChanged();
      } else {
        typeEnvBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder addTypeEnv(
        int index, com.google.api.expr.v1alpha1.Decl value) {
      if (typeEnvBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeEnvIsMutable();
        typeEnv_.add(index, value);
        onChanged();
      } else {
        typeEnvBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder addTypeEnv(
        com.google.api.expr.v1alpha1.Decl.Builder builderForValue) {
      if (typeEnvBuilder_ == null) {
        ensureTypeEnvIsMutable();
        typeEnv_.add(builderForValue.build());
        onChanged();
      } else {
        typeEnvBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder addTypeEnv(
        int index, com.google.api.expr.v1alpha1.Decl.Builder builderForValue) {
      if (typeEnvBuilder_ == null) {
        ensureTypeEnvIsMutable();
        typeEnv_.add(index, builderForValue.build());
        onChanged();
      } else {
        typeEnvBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder addAllTypeEnv(
        java.lang.Iterable<? extends com.google.api.expr.v1alpha1.Decl> values) {
      if (typeEnvBuilder_ == null) {
        ensureTypeEnvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, typeEnv_);
        onChanged();
      } else {
        typeEnvBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder clearTypeEnv() {
      if (typeEnvBuilder_ == null) {
        typeEnv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        typeEnvBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public Builder removeTypeEnv(int index) {
      if (typeEnvBuilder_ == null) {
        ensureTypeEnvIsMutable();
        typeEnv_.remove(index);
        onChanged();
      } else {
        typeEnvBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public com.google.api.expr.v1alpha1.Decl.Builder getTypeEnvBuilder(
        int index) {
      return getTypeEnvFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public com.google.api.expr.v1alpha1.DeclOrBuilder getTypeEnvOrBuilder(
        int index) {
      if (typeEnvBuilder_ == null) {
        return typeEnv_.get(index);  } else {
        return typeEnvBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public java.util.List<? extends com.google.api.expr.v1alpha1.DeclOrBuilder> 
         getTypeEnvOrBuilderList() {
      if (typeEnvBuilder_ != null) {
        return typeEnvBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(typeEnv_);
      }
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public com.google.api.expr.v1alpha1.Decl.Builder addTypeEnvBuilder() {
      return getTypeEnvFieldBuilder().addBuilder(
          com.google.api.expr.v1alpha1.Decl.getDefaultInstance());
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public com.google.api.expr.v1alpha1.Decl.Builder addTypeEnvBuilder(
        int index) {
      return getTypeEnvFieldBuilder().addBuilder(
          index, com.google.api.expr.v1alpha1.Decl.getDefaultInstance());
    }
    /**
     * <pre>
     * Declarations of types for external variables and functions.
     * Required if program uses external variables or functions
     * not in the default environment.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1alpha1.Decl type_env = 2;</code>
     */
    public java.util.List<com.google.api.expr.v1alpha1.Decl.Builder> 
         getTypeEnvBuilderList() {
      return getTypeEnvFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1alpha1.Decl, com.google.api.expr.v1alpha1.Decl.Builder, com.google.api.expr.v1alpha1.DeclOrBuilder> 
        getTypeEnvFieldBuilder() {
      if (typeEnvBuilder_ == null) {
        typeEnvBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.api.expr.v1alpha1.Decl, com.google.api.expr.v1alpha1.Decl.Builder, com.google.api.expr.v1alpha1.DeclOrBuilder>(
                typeEnv_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        typeEnv_ = null;
      }
      return typeEnvBuilder_;
    }

    private java.lang.Object container_ = "";
    /**
     * <pre>
     * The protocol buffer context.  See "Name Resolution" in the
     * Language Definition.
     * </pre>
     *
     * <code>string container = 3;</code>
     */
    public java.lang.String getContainer() {
      java.lang.Object ref = container_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        container_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The protocol buffer context.  See "Name Resolution" in the
     * Language Definition.
     * </pre>
     *
     * <code>string container = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContainerBytes() {
      java.lang.Object ref = container_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        container_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The protocol buffer context.  See "Name Resolution" in the
     * Language Definition.
     * </pre>
     *
     * <code>string container = 3;</code>
     */
    public Builder setContainer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      container_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The protocol buffer context.  See "Name Resolution" in the
     * Language Definition.
     * </pre>
     *
     * <code>string container = 3;</code>
     */
    public Builder clearContainer() {
      
      container_ = getDefaultInstance().getContainer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The protocol buffer context.  See "Name Resolution" in the
     * Language Definition.
     * </pre>
     *
     * <code>string container = 3;</code>
     */
    public Builder setContainerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      container_ = value;
      onChanged();
      return this;
    }

    private boolean noStdEnv_ ;
    /**
     * <pre>
     * If true, use only the declarations in
     * [type_env][google.api.expr.v1alpha1.CheckRequest.type_env].  If false
     * (default), add declarations for the standard definitions to the type
     * environment.  See "Standard Definitions" in the Language Definition.
     * </pre>
     *
     * <code>bool no_std_env = 4;</code>
     */
    public boolean getNoStdEnv() {
      return noStdEnv_;
    }
    /**
     * <pre>
     * If true, use only the declarations in
     * [type_env][google.api.expr.v1alpha1.CheckRequest.type_env].  If false
     * (default), add declarations for the standard definitions to the type
     * environment.  See "Standard Definitions" in the Language Definition.
     * </pre>
     *
     * <code>bool no_std_env = 4;</code>
     */
    public Builder setNoStdEnv(boolean value) {
      
      noStdEnv_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, use only the declarations in
     * [type_env][google.api.expr.v1alpha1.CheckRequest.type_env].  If false
     * (default), add declarations for the standard definitions to the type
     * environment.  See "Standard Definitions" in the Language Definition.
     * </pre>
     *
     * <code>bool no_std_env = 4;</code>
     */
    public Builder clearNoStdEnv() {
      
      noStdEnv_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.api.expr.v1alpha1.CheckRequest)
  }

  // @@protoc_insertion_point(class_scope:google.api.expr.v1alpha1.CheckRequest)
  private static final com.google.api.expr.v1alpha1.CheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.api.expr.v1alpha1.CheckRequest();
  }

  public static com.google.api.expr.v1alpha1.CheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckRequest>() {
    @java.lang.Override
    public CheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.api.expr.v1alpha1.CheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

