// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1alpha1/checked.proto

package com.google.api.expr.v1alpha1;

public final class DeclProto {
  private DeclProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_CheckedExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_CheckedExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_CheckedExpr_ReferenceMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_CheckedExpr_ReferenceMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_CheckedExpr_TypeMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_CheckedExpr_TypeMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Type_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Type_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Type_ListType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Type_ListType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Type_MapType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Type_MapType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Type_FunctionType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Type_FunctionType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Type_AbstractType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Type_AbstractType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Decl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Decl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Decl_IdentDecl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Decl_IdentDecl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_Overload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_Overload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Reference_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&google/api/expr/v1alpha1/checked.proto" +
      "\022\030google.api.expr.v1alpha1\032%google/api/e" +
      "xpr/v1alpha1/syntax.proto\032\033google/protob" +
      "uf/empty.proto\032\034google/protobuf/struct.p" +
      "roto\"\266\003\n\013CheckedExpr\022N\n\rreference_map\030\002 " +
      "\003(\01327.google.api.expr.v1alpha1.CheckedEx" +
      "pr.ReferenceMapEntry\022D\n\010type_map\030\003 \003(\01322" +
      ".google.api.expr.v1alpha1.CheckedExpr.Ty" +
      "peMapEntry\0229\n\013source_info\030\005 \001(\0132$.google" +
      ".api.expr.v1alpha1.SourceInfo\022,\n\004expr\030\004 " +
      "\001(\0132\036.google.api.expr.v1alpha1.Expr\032X\n\021R" +
      "eferenceMapEntry\022\013\n\003key\030\001 \001(\003\0222\n\005value\030\002" +
      " \001(\0132#.google.api.expr.v1alpha1.Referenc" +
      "e:\0028\001\032N\n\014TypeMapEntry\022\013\n\003key\030\001 \001(\003\022-\n\005va" +
      "lue\030\002 \001(\0132\036.google.api.expr.v1alpha1.Typ" +
      "e:\0028\001\"\202\n\n\004Type\022%\n\003dyn\030\001 \001(\0132\026.google.pro" +
      "tobuf.EmptyH\000\022*\n\004null\030\002 \001(\0162\032.google.pro" +
      "tobuf.NullValueH\000\022A\n\tprimitive\030\003 \001(\0162,.g" +
      "oogle.api.expr.v1alpha1.Type.PrimitiveTy" +
      "peH\000\022?\n\007wrapper\030\004 \001(\0162,.google.api.expr." +
      "v1alpha1.Type.PrimitiveTypeH\000\022B\n\nwell_kn" +
      "own\030\005 \001(\0162,.google.api.expr.v1alpha1.Typ" +
      "e.WellKnownTypeH\000\022<\n\tlist_type\030\006 \001(\0132\'.g" +
      "oogle.api.expr.v1alpha1.Type.ListTypeH\000\022" +
      ":\n\010map_type\030\007 \001(\0132&.google.api.expr.v1al" +
      "pha1.Type.MapTypeH\000\022?\n\010function\030\010 \001(\0132+." +
      "google.api.expr.v1alpha1.Type.FunctionTy" +
      "peH\000\022\026\n\014message_type\030\t \001(\tH\000\022\024\n\ntype_par" +
      "am\030\n \001(\tH\000\022.\n\004type\030\013 \001(\0132\036.google.api.ex" +
      "pr.v1alpha1.TypeH\000\022\'\n\005error\030\014 \001(\0132\026.goog" +
      "le.protobuf.EmptyH\000\022D\n\rabstract_type\030\016 \001" +
      "(\0132+.google.api.expr.v1alpha1.Type.Abstr" +
      "actTypeH\000\032=\n\010ListType\0221\n\telem_type\030\001 \001(\013" +
      "2\036.google.api.expr.v1alpha1.Type\032o\n\007MapT" +
      "ype\0220\n\010key_type\030\001 \001(\0132\036.google.api.expr." +
      "v1alpha1.Type\0222\n\nvalue_type\030\002 \001(\0132\036.goog" +
      "le.api.expr.v1alpha1.Type\032v\n\014FunctionTyp" +
      "e\0223\n\013result_type\030\001 \001(\0132\036.google.api.expr" +
      ".v1alpha1.Type\0221\n\targ_types\030\002 \003(\0132\036.goog" +
      "le.api.expr.v1alpha1.Type\032U\n\014AbstractTyp" +
      "e\022\014\n\004name\030\001 \001(\t\0227\n\017parameter_types\030\002 \003(\013" +
      "2\036.google.api.expr.v1alpha1.Type\"s\n\rPrim" +
      "itiveType\022\036\n\032PRIMITIVE_TYPE_UNSPECIFIED\020" +
      "\000\022\010\n\004BOOL\020\001\022\t\n\005INT64\020\002\022\n\n\006UINT64\020\003\022\n\n\006DO" +
      "UBLE\020\004\022\n\n\006STRING\020\005\022\t\n\005BYTES\020\006\"V\n\rWellKno" +
      "wnType\022\037\n\033WELL_KNOWN_TYPE_UNSPECIFIED\020\000\022" +
      "\007\n\003ANY\020\001\022\r\n\tTIMESTAMP\020\002\022\014\n\010DURATION\020\003B\013\n" +
      "\ttype_kind\"\271\004\n\004Decl\022\014\n\004name\030\001 \001(\t\0229\n\005ide" +
      "nt\030\002 \001(\0132(.google.api.expr.v1alpha1.Decl" +
      ".IdentDeclH\000\022?\n\010function\030\003 \001(\0132+.google." +
      "api.expr.v1alpha1.Decl.FunctionDeclH\000\032y\n" +
      "\tIdentDecl\022,\n\004type\030\001 \001(\0132\036.google.api.ex" +
      "pr.v1alpha1.Type\0221\n\005value\030\002 \001(\0132\".google" +
      ".api.expr.v1alpha1.Constant\022\013\n\003doc\030\003 \001(\t" +
      "\032\236\002\n\014FunctionDecl\022G\n\toverloads\030\001 \003(\01324.g" +
      "oogle.api.expr.v1alpha1.Decl.FunctionDec" +
      "l.Overload\032\304\001\n\010Overload\022\023\n\013overload_id\030\001" +
      " \001(\t\022.\n\006params\030\002 \003(\0132\036.google.api.expr.v" +
      "1alpha1.Type\022\023\n\013type_params\030\003 \003(\t\0223\n\013res" +
      "ult_type\030\004 \001(\0132\036.google.api.expr.v1alpha" +
      "1.Type\022\034\n\024is_instance_function\030\005 \001(\010\022\013\n\003" +
      "doc\030\006 \001(\tB\013\n\tdecl_kind\"a\n\tReference\022\014\n\004n" +
      "ame\030\001 \001(\t\022\023\n\013overload_id\030\003 \003(\t\0221\n\005value\030" +
      "\004 \001(\0132\".google.api.expr.v1alpha1.Constan" +
      "tBl\n\034com.google.api.expr.v1alpha1B\tDeclP" +
      "rotoP\001Z<google.golang.org/genproto/googl" +
      "eapis/api/expr/v1alpha1;expr\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.expr.v1alpha1.SyntaxProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        }, assigner);
    internal_static_google_api_expr_v1alpha1_CheckedExpr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_expr_v1alpha1_CheckedExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_CheckedExpr_descriptor,
        new java.lang.String[] { "ReferenceMap", "TypeMap", "SourceInfo", "Expr", });
    internal_static_google_api_expr_v1alpha1_CheckedExpr_ReferenceMapEntry_descriptor =
      internal_static_google_api_expr_v1alpha1_CheckedExpr_descriptor.getNestedTypes().get(0);
    internal_static_google_api_expr_v1alpha1_CheckedExpr_ReferenceMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_CheckedExpr_ReferenceMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_api_expr_v1alpha1_CheckedExpr_TypeMapEntry_descriptor =
      internal_static_google_api_expr_v1alpha1_CheckedExpr_descriptor.getNestedTypes().get(1);
    internal_static_google_api_expr_v1alpha1_CheckedExpr_TypeMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_CheckedExpr_TypeMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_api_expr_v1alpha1_Type_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_api_expr_v1alpha1_Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Type_descriptor,
        new java.lang.String[] { "Dyn", "Null", "Primitive", "Wrapper", "WellKnown", "ListType", "MapType", "Function", "MessageType", "TypeParam", "Type", "Error", "AbstractType", "TypeKind", });
    internal_static_google_api_expr_v1alpha1_Type_ListType_descriptor =
      internal_static_google_api_expr_v1alpha1_Type_descriptor.getNestedTypes().get(0);
    internal_static_google_api_expr_v1alpha1_Type_ListType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Type_ListType_descriptor,
        new java.lang.String[] { "ElemType", });
    internal_static_google_api_expr_v1alpha1_Type_MapType_descriptor =
      internal_static_google_api_expr_v1alpha1_Type_descriptor.getNestedTypes().get(1);
    internal_static_google_api_expr_v1alpha1_Type_MapType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Type_MapType_descriptor,
        new java.lang.String[] { "KeyType", "ValueType", });
    internal_static_google_api_expr_v1alpha1_Type_FunctionType_descriptor =
      internal_static_google_api_expr_v1alpha1_Type_descriptor.getNestedTypes().get(2);
    internal_static_google_api_expr_v1alpha1_Type_FunctionType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Type_FunctionType_descriptor,
        new java.lang.String[] { "ResultType", "ArgTypes", });
    internal_static_google_api_expr_v1alpha1_Type_AbstractType_descriptor =
      internal_static_google_api_expr_v1alpha1_Type_descriptor.getNestedTypes().get(3);
    internal_static_google_api_expr_v1alpha1_Type_AbstractType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Type_AbstractType_descriptor,
        new java.lang.String[] { "Name", "ParameterTypes", });
    internal_static_google_api_expr_v1alpha1_Decl_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_api_expr_v1alpha1_Decl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Decl_descriptor,
        new java.lang.String[] { "Name", "Ident", "Function", "DeclKind", });
    internal_static_google_api_expr_v1alpha1_Decl_IdentDecl_descriptor =
      internal_static_google_api_expr_v1alpha1_Decl_descriptor.getNestedTypes().get(0);
    internal_static_google_api_expr_v1alpha1_Decl_IdentDecl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Decl_IdentDecl_descriptor,
        new java.lang.String[] { "Type", "Value", "Doc", });
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_descriptor =
      internal_static_google_api_expr_v1alpha1_Decl_descriptor.getNestedTypes().get(1);
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_descriptor,
        new java.lang.String[] { "Overloads", });
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_Overload_descriptor =
      internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_descriptor.getNestedTypes().get(0);
    internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_Overload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Decl_FunctionDecl_Overload_descriptor,
        new java.lang.String[] { "OverloadId", "Params", "TypeParams", "ResultType", "IsInstanceFunction", "Doc", });
    internal_static_google_api_expr_v1alpha1_Reference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_api_expr_v1alpha1_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Reference_descriptor,
        new java.lang.String[] { "Name", "OverloadId", "Value", });
    com.google.api.expr.v1alpha1.SyntaxProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
