// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1alpha1/explain.proto

package com.google.api.expr.v1alpha1;

public final class ExplainProto {
  private ExplainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Explain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Explain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_expr_v1alpha1_Explain_ExprStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_expr_v1alpha1_Explain_ExprStep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&google/api/expr/v1alpha1/explain.proto" +
      "\022\030google.api.expr.v1alpha1\032$google/api/e" +
      "xpr/v1alpha1/value.proto\"\253\001\n\007Explain\022/\n\006" +
      "values\030\001 \003(\0132\037.google.api.expr.v1alpha1." +
      "Value\022>\n\nexpr_steps\030\002 \003(\0132*.google.api.e" +
      "xpr.v1alpha1.Explain.ExprStep\032+\n\010ExprSte" +
      "p\022\n\n\002id\030\001 \001(\003\022\023\n\013value_index\030\002 \001(\005:\002\030\001Bo" +
      "\n\034com.google.api.expr.v1alpha1B\014ExplainP" +
      "rotoP\001Z<google.golang.org/genproto/googl" +
      "eapis/api/expr/v1alpha1;expr\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.expr.v1alpha1.ValueProto.getDescriptor(),
        }, assigner);
    internal_static_google_api_expr_v1alpha1_Explain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_expr_v1alpha1_Explain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Explain_descriptor,
        new java.lang.String[] { "Values", "ExprSteps", });
    internal_static_google_api_expr_v1alpha1_Explain_ExprStep_descriptor =
      internal_static_google_api_expr_v1alpha1_Explain_descriptor.getNestedTypes().get(0);
    internal_static_google_api_expr_v1alpha1_Explain_ExprStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_expr_v1alpha1_Explain_ExprStep_descriptor,
        new java.lang.String[] { "Id", "ValueIndex", });
    com.google.api.expr.v1alpha1.ValueProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
