// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1alpha1/conformance_service.proto

package com.google.api.expr.v1alpha1;

public interface ParseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.expr.v1alpha1.ParseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Source text in CEL syntax.
   * </pre>
   *
   * <code>string cel_source = 1;</code>
   */
  java.lang.String getCelSource();
  /**
   * <pre>
   * Required. Source text in CEL syntax.
   * </pre>
   *
   * <code>string cel_source = 1;</code>
   */
  com.google.protobuf.ByteString
      getCelSourceBytes();

  /**
   * <pre>
   * Tag for version of CEL syntax, for future use.
   * </pre>
   *
   * <code>string syntax_version = 2;</code>
   */
  java.lang.String getSyntaxVersion();
  /**
   * <pre>
   * Tag for version of CEL syntax, for future use.
   * </pre>
   *
   * <code>string syntax_version = 2;</code>
   */
  com.google.protobuf.ByteString
      getSyntaxVersionBytes();

  /**
   * <pre>
   * File or resource for source text, used in
   * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
   * </pre>
   *
   * <code>string source_location = 3;</code>
   */
  java.lang.String getSourceLocation();
  /**
   * <pre>
   * File or resource for source text, used in
   * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
   * </pre>
   *
   * <code>string source_location = 3;</code>
   */
  com.google.protobuf.ByteString
      getSourceLocationBytes();

  /**
   * <pre>
   * Prevent macro expansion.  See "Macros" in Language Defiinition.
   * </pre>
   *
   * <code>bool disable_macros = 4;</code>
   */
  boolean getDisableMacros();
}
