// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1alpha1/conformance_service.proto

package com.google.api.expr.v1alpha1;

/**
 * <pre>
 * Request message for the Parse method.
 * </pre>
 *
 * Protobuf type {@code google.api.expr.v1alpha1.ParseRequest}
 */
public  final class ParseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.expr.v1alpha1.ParseRequest)
    ParseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParseRequest.newBuilder() to construct.
  private ParseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParseRequest() {
    celSource_ = "";
    syntaxVersion_ = "";
    sourceLocation_ = "";
    disableMacros_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParseRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            celSource_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            syntaxVersion_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceLocation_ = s;
            break;
          }
          case 32: {

            disableMacros_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_ParseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_ParseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.api.expr.v1alpha1.ParseRequest.class, com.google.api.expr.v1alpha1.ParseRequest.Builder.class);
  }

  public static final int CEL_SOURCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object celSource_;
  /**
   * <pre>
   * Required. Source text in CEL syntax.
   * </pre>
   *
   * <code>string cel_source = 1;</code>
   */
  public java.lang.String getCelSource() {
    java.lang.Object ref = celSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      celSource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Source text in CEL syntax.
   * </pre>
   *
   * <code>string cel_source = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCelSourceBytes() {
    java.lang.Object ref = celSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      celSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYNTAX_VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object syntaxVersion_;
  /**
   * <pre>
   * Tag for version of CEL syntax, for future use.
   * </pre>
   *
   * <code>string syntax_version = 2;</code>
   */
  public java.lang.String getSyntaxVersion() {
    java.lang.Object ref = syntaxVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      syntaxVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tag for version of CEL syntax, for future use.
   * </pre>
   *
   * <code>string syntax_version = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSyntaxVersionBytes() {
    java.lang.Object ref = syntaxVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      syntaxVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_LOCATION_FIELD_NUMBER = 3;
  private volatile java.lang.Object sourceLocation_;
  /**
   * <pre>
   * File or resource for source text, used in
   * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
   * </pre>
   *
   * <code>string source_location = 3;</code>
   */
  public java.lang.String getSourceLocation() {
    java.lang.Object ref = sourceLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceLocation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * File or resource for source text, used in
   * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
   * </pre>
   *
   * <code>string source_location = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSourceLocationBytes() {
    java.lang.Object ref = sourceLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISABLE_MACROS_FIELD_NUMBER = 4;
  private boolean disableMacros_;
  /**
   * <pre>
   * Prevent macro expansion.  See "Macros" in Language Defiinition.
   * </pre>
   *
   * <code>bool disable_macros = 4;</code>
   */
  public boolean getDisableMacros() {
    return disableMacros_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCelSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, celSource_);
    }
    if (!getSyntaxVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, syntaxVersion_);
    }
    if (!getSourceLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceLocation_);
    }
    if (disableMacros_ != false) {
      output.writeBool(4, disableMacros_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCelSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, celSource_);
    }
    if (!getSyntaxVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, syntaxVersion_);
    }
    if (!getSourceLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceLocation_);
    }
    if (disableMacros_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, disableMacros_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.api.expr.v1alpha1.ParseRequest)) {
      return super.equals(obj);
    }
    com.google.api.expr.v1alpha1.ParseRequest other = (com.google.api.expr.v1alpha1.ParseRequest) obj;

    boolean result = true;
    result = result && getCelSource()
        .equals(other.getCelSource());
    result = result && getSyntaxVersion()
        .equals(other.getSyntaxVersion());
    result = result && getSourceLocation()
        .equals(other.getSourceLocation());
    result = result && (getDisableMacros()
        == other.getDisableMacros());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CEL_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getCelSource().hashCode();
    hash = (37 * hash) + SYNTAX_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getSyntaxVersion().hashCode();
    hash = (37 * hash) + SOURCE_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getSourceLocation().hashCode();
    hash = (37 * hash) + DISABLE_MACROS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableMacros());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1alpha1.ParseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.expr.v1alpha1.ParseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for the Parse method.
   * </pre>
   *
   * Protobuf type {@code google.api.expr.v1alpha1.ParseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.expr.v1alpha1.ParseRequest)
      com.google.api.expr.v1alpha1.ParseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_ParseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_ParseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.api.expr.v1alpha1.ParseRequest.class, com.google.api.expr.v1alpha1.ParseRequest.Builder.class);
    }

    // Construct using com.google.api.expr.v1alpha1.ParseRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      celSource_ = "";

      syntaxVersion_ = "";

      sourceLocation_ = "";

      disableMacros_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.api.expr.v1alpha1.ConformanceServiceProto.internal_static_google_api_expr_v1alpha1_ParseRequest_descriptor;
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.ParseRequest getDefaultInstanceForType() {
      return com.google.api.expr.v1alpha1.ParseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.ParseRequest build() {
      com.google.api.expr.v1alpha1.ParseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.api.expr.v1alpha1.ParseRequest buildPartial() {
      com.google.api.expr.v1alpha1.ParseRequest result = new com.google.api.expr.v1alpha1.ParseRequest(this);
      result.celSource_ = celSource_;
      result.syntaxVersion_ = syntaxVersion_;
      result.sourceLocation_ = sourceLocation_;
      result.disableMacros_ = disableMacros_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.api.expr.v1alpha1.ParseRequest) {
        return mergeFrom((com.google.api.expr.v1alpha1.ParseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.api.expr.v1alpha1.ParseRequest other) {
      if (other == com.google.api.expr.v1alpha1.ParseRequest.getDefaultInstance()) return this;
      if (!other.getCelSource().isEmpty()) {
        celSource_ = other.celSource_;
        onChanged();
      }
      if (!other.getSyntaxVersion().isEmpty()) {
        syntaxVersion_ = other.syntaxVersion_;
        onChanged();
      }
      if (!other.getSourceLocation().isEmpty()) {
        sourceLocation_ = other.sourceLocation_;
        onChanged();
      }
      if (other.getDisableMacros() != false) {
        setDisableMacros(other.getDisableMacros());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.api.expr.v1alpha1.ParseRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.api.expr.v1alpha1.ParseRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object celSource_ = "";
    /**
     * <pre>
     * Required. Source text in CEL syntax.
     * </pre>
     *
     * <code>string cel_source = 1;</code>
     */
    public java.lang.String getCelSource() {
      java.lang.Object ref = celSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        celSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. Source text in CEL syntax.
     * </pre>
     *
     * <code>string cel_source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCelSourceBytes() {
      java.lang.Object ref = celSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        celSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Source text in CEL syntax.
     * </pre>
     *
     * <code>string cel_source = 1;</code>
     */
    public Builder setCelSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      celSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Source text in CEL syntax.
     * </pre>
     *
     * <code>string cel_source = 1;</code>
     */
    public Builder clearCelSource() {
      
      celSource_ = getDefaultInstance().getCelSource();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Source text in CEL syntax.
     * </pre>
     *
     * <code>string cel_source = 1;</code>
     */
    public Builder setCelSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      celSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object syntaxVersion_ = "";
    /**
     * <pre>
     * Tag for version of CEL syntax, for future use.
     * </pre>
     *
     * <code>string syntax_version = 2;</code>
     */
    public java.lang.String getSyntaxVersion() {
      java.lang.Object ref = syntaxVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        syntaxVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tag for version of CEL syntax, for future use.
     * </pre>
     *
     * <code>string syntax_version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSyntaxVersionBytes() {
      java.lang.Object ref = syntaxVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        syntaxVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tag for version of CEL syntax, for future use.
     * </pre>
     *
     * <code>string syntax_version = 2;</code>
     */
    public Builder setSyntaxVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      syntaxVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tag for version of CEL syntax, for future use.
     * </pre>
     *
     * <code>string syntax_version = 2;</code>
     */
    public Builder clearSyntaxVersion() {
      
      syntaxVersion_ = getDefaultInstance().getSyntaxVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tag for version of CEL syntax, for future use.
     * </pre>
     *
     * <code>string syntax_version = 2;</code>
     */
    public Builder setSyntaxVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      syntaxVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceLocation_ = "";
    /**
     * <pre>
     * File or resource for source text, used in
     * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
     * </pre>
     *
     * <code>string source_location = 3;</code>
     */
    public java.lang.String getSourceLocation() {
      java.lang.Object ref = sourceLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * File or resource for source text, used in
     * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
     * </pre>
     *
     * <code>string source_location = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceLocationBytes() {
      java.lang.Object ref = sourceLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * File or resource for source text, used in
     * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
     * </pre>
     *
     * <code>string source_location = 3;</code>
     */
    public Builder setSourceLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File or resource for source text, used in
     * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
     * </pre>
     *
     * <code>string source_location = 3;</code>
     */
    public Builder clearSourceLocation() {
      
      sourceLocation_ = getDefaultInstance().getSourceLocation();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File or resource for source text, used in
     * [SourceInfo][google.api.expr.v1alpha1.SourceInfo].
     * </pre>
     *
     * <code>string source_location = 3;</code>
     */
    public Builder setSourceLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceLocation_ = value;
      onChanged();
      return this;
    }

    private boolean disableMacros_ ;
    /**
     * <pre>
     * Prevent macro expansion.  See "Macros" in Language Defiinition.
     * </pre>
     *
     * <code>bool disable_macros = 4;</code>
     */
    public boolean getDisableMacros() {
      return disableMacros_;
    }
    /**
     * <pre>
     * Prevent macro expansion.  See "Macros" in Language Defiinition.
     * </pre>
     *
     * <code>bool disable_macros = 4;</code>
     */
    public Builder setDisableMacros(boolean value) {
      
      disableMacros_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prevent macro expansion.  See "Macros" in Language Defiinition.
     * </pre>
     *
     * <code>bool disable_macros = 4;</code>
     */
    public Builder clearDisableMacros() {
      
      disableMacros_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.api.expr.v1alpha1.ParseRequest)
  }

  // @@protoc_insertion_point(class_scope:google.api.expr.v1alpha1.ParseRequest)
  private static final com.google.api.expr.v1alpha1.ParseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.api.expr.v1alpha1.ParseRequest();
  }

  public static com.google.api.expr.v1alpha1.ParseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseRequest>
      PARSER = new com.google.protobuf.AbstractParser<ParseRequest>() {
    @java.lang.Override
    public ParseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ParseRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.api.expr.v1alpha1.ParseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

