// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1beta1/eval.proto

package com.google.api.expr.v1beta1;

/**
 * <pre>
 * The state of an evaluation.
 * Can represent an initial, partial, or completed state of evaluation.
 * </pre>
 *
 * Protobuf type {@code google.api.expr.v1beta1.EvalState}
 */
public  final class EvalState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.expr.v1beta1.EvalState)
    EvalStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EvalState.newBuilder() to construct.
  private EvalState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EvalState() {
    values_ = java.util.Collections.emptyList();
    results_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EvalState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              values_ = new java.util.ArrayList<com.google.api.expr.v1beta1.ExprValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            values_.add(
                input.readMessage(com.google.api.expr.v1beta1.ExprValue.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              results_ = new java.util.ArrayList<com.google.api.expr.v1beta1.EvalState.Result>();
              mutable_bitField0_ |= 0x00000002;
            }
            results_.add(
                input.readMessage(com.google.api.expr.v1beta1.EvalState.Result.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        values_ = java.util.Collections.unmodifiableList(values_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.api.expr.v1beta1.EvalState.class, com.google.api.expr.v1beta1.EvalState.Builder.class);
  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.api.expr.v1beta1.EvalState.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    boolean hasExpr();
    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    com.google.api.expr.v1beta1.IdRef getExpr();
    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    com.google.api.expr.v1beta1.IdRefOrBuilder getExprOrBuilder();

    /**
     * <pre>
     * The index in `values` of the resulting value.
     * </pre>
     *
     * <code>int32 value = 2;</code>
     */
    int getValue();
  }
  /**
   * <pre>
   * A single evaluation result.
   * </pre>
   *
   * Protobuf type {@code google.api.expr.v1beta1.EvalState.Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.api.expr.v1beta1.EvalState.Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      value_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.api.expr.v1beta1.IdRef.Builder subBuilder = null;
              if (expr_ != null) {
                subBuilder = expr_.toBuilder();
              }
              expr_ = input.readMessage(com.google.api.expr.v1beta1.IdRef.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(expr_);
                expr_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              value_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_Result_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.api.expr.v1beta1.EvalState.Result.class, com.google.api.expr.v1beta1.EvalState.Result.Builder.class);
    }

    public static final int EXPR_FIELD_NUMBER = 1;
    private com.google.api.expr.v1beta1.IdRef expr_;
    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    public boolean hasExpr() {
      return expr_ != null;
    }
    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRef getExpr() {
      return expr_ == null ? com.google.api.expr.v1beta1.IdRef.getDefaultInstance() : expr_;
    }
    /**
     * <pre>
     * The expression this result is for.
     * </pre>
     *
     * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRefOrBuilder getExprOrBuilder() {
      return getExpr();
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <pre>
     * The index in `values` of the resulting value.
     * </pre>
     *
     * <code>int32 value = 2;</code>
     */
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (expr_ != null) {
        output.writeMessage(1, getExpr());
      }
      if (value_ != 0) {
        output.writeInt32(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (expr_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getExpr());
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.api.expr.v1beta1.EvalState.Result)) {
        return super.equals(obj);
      }
      com.google.api.expr.v1beta1.EvalState.Result other = (com.google.api.expr.v1beta1.EvalState.Result) obj;

      boolean result = true;
      result = result && (hasExpr() == other.hasExpr());
      if (hasExpr()) {
        result = result && getExpr()
            .equals(other.getExpr());
      }
      result = result && (getValue()
          == other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasExpr()) {
        hash = (37 * hash) + EXPR_FIELD_NUMBER;
        hash = (53 * hash) + getExpr().hashCode();
      }
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.api.expr.v1beta1.EvalState.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.api.expr.v1beta1.EvalState.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A single evaluation result.
     * </pre>
     *
     * Protobuf type {@code google.api.expr.v1beta1.EvalState.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.api.expr.v1beta1.EvalState.Result)
        com.google.api.expr.v1beta1.EvalState.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.api.expr.v1beta1.EvalState.Result.class, com.google.api.expr.v1beta1.EvalState.Result.Builder.class);
      }

      // Construct using com.google.api.expr.v1beta1.EvalState.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (exprBuilder_ == null) {
          expr_ = null;
        } else {
          expr_ = null;
          exprBuilder_ = null;
        }
        value_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_Result_descriptor;
      }

      @java.lang.Override
      public com.google.api.expr.v1beta1.EvalState.Result getDefaultInstanceForType() {
        return com.google.api.expr.v1beta1.EvalState.Result.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.api.expr.v1beta1.EvalState.Result build() {
        com.google.api.expr.v1beta1.EvalState.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.api.expr.v1beta1.EvalState.Result buildPartial() {
        com.google.api.expr.v1beta1.EvalState.Result result = new com.google.api.expr.v1beta1.EvalState.Result(this);
        if (exprBuilder_ == null) {
          result.expr_ = expr_;
        } else {
          result.expr_ = exprBuilder_.build();
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.api.expr.v1beta1.EvalState.Result) {
          return mergeFrom((com.google.api.expr.v1beta1.EvalState.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.api.expr.v1beta1.EvalState.Result other) {
        if (other == com.google.api.expr.v1beta1.EvalState.Result.getDefaultInstance()) return this;
        if (other.hasExpr()) {
          mergeExpr(other.getExpr());
        }
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.api.expr.v1beta1.EvalState.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.api.expr.v1beta1.EvalState.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.api.expr.v1beta1.IdRef expr_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder> exprBuilder_;
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public boolean hasExpr() {
        return exprBuilder_ != null || expr_ != null;
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public com.google.api.expr.v1beta1.IdRef getExpr() {
        if (exprBuilder_ == null) {
          return expr_ == null ? com.google.api.expr.v1beta1.IdRef.getDefaultInstance() : expr_;
        } else {
          return exprBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public Builder setExpr(com.google.api.expr.v1beta1.IdRef value) {
        if (exprBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expr_ = value;
          onChanged();
        } else {
          exprBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public Builder setExpr(
          com.google.api.expr.v1beta1.IdRef.Builder builderForValue) {
        if (exprBuilder_ == null) {
          expr_ = builderForValue.build();
          onChanged();
        } else {
          exprBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public Builder mergeExpr(com.google.api.expr.v1beta1.IdRef value) {
        if (exprBuilder_ == null) {
          if (expr_ != null) {
            expr_ =
              com.google.api.expr.v1beta1.IdRef.newBuilder(expr_).mergeFrom(value).buildPartial();
          } else {
            expr_ = value;
          }
          onChanged();
        } else {
          exprBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public Builder clearExpr() {
        if (exprBuilder_ == null) {
          expr_ = null;
          onChanged();
        } else {
          expr_ = null;
          exprBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public com.google.api.expr.v1beta1.IdRef.Builder getExprBuilder() {
        
        onChanged();
        return getExprFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      public com.google.api.expr.v1beta1.IdRefOrBuilder getExprOrBuilder() {
        if (exprBuilder_ != null) {
          return exprBuilder_.getMessageOrBuilder();
        } else {
          return expr_ == null ?
              com.google.api.expr.v1beta1.IdRef.getDefaultInstance() : expr_;
        }
      }
      /**
       * <pre>
       * The expression this result is for.
       * </pre>
       *
       * <code>.google.api.expr.v1beta1.IdRef expr = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder> 
          getExprFieldBuilder() {
        if (exprBuilder_ == null) {
          exprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder>(
                  getExpr(),
                  getParentForChildren(),
                  isClean());
          expr_ = null;
        }
        return exprBuilder_;
      }

      private int value_ ;
      /**
       * <pre>
       * The index in `values` of the resulting value.
       * </pre>
       *
       * <code>int32 value = 2;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <pre>
       * The index in `values` of the resulting value.
       * </pre>
       *
       * <code>int32 value = 2;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The index in `values` of the resulting value.
       * </pre>
       *
       * <code>int32 value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.api.expr.v1beta1.EvalState.Result)
    }

    // @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.EvalState.Result)
    private static final com.google.api.expr.v1beta1.EvalState.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.api.expr.v1beta1.EvalState.Result();
    }

    public static com.google.api.expr.v1beta1.EvalState.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @java.lang.Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.EvalState.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int VALUES_FIELD_NUMBER = 1;
  private java.util.List<com.google.api.expr.v1beta1.ExprValue> values_;
  /**
   * <pre>
   * The unique values referenced in this message.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
   */
  public java.util.List<com.google.api.expr.v1beta1.ExprValue> getValuesList() {
    return values_;
  }
  /**
   * <pre>
   * The unique values referenced in this message.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
   */
  public java.util.List<? extends com.google.api.expr.v1beta1.ExprValueOrBuilder> 
      getValuesOrBuilderList() {
    return values_;
  }
  /**
   * <pre>
   * The unique values referenced in this message.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
   */
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <pre>
   * The unique values referenced in this message.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
   */
  public com.google.api.expr.v1beta1.ExprValue getValues(int index) {
    return values_.get(index);
  }
  /**
   * <pre>
   * The unique values referenced in this message.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
   */
  public com.google.api.expr.v1beta1.ExprValueOrBuilder getValuesOrBuilder(
      int index) {
    return values_.get(index);
  }

  public static final int RESULTS_FIELD_NUMBER = 3;
  private java.util.List<com.google.api.expr.v1beta1.EvalState.Result> results_;
  /**
   * <pre>
   * An ordered list of results.
   * Tracks the flow of evaluation through the expression.
   * May be sparse.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
   */
  public java.util.List<com.google.api.expr.v1beta1.EvalState.Result> getResultsList() {
    return results_;
  }
  /**
   * <pre>
   * An ordered list of results.
   * Tracks the flow of evaluation through the expression.
   * May be sparse.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
   */
  public java.util.List<? extends com.google.api.expr.v1beta1.EvalState.ResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <pre>
   * An ordered list of results.
   * Tracks the flow of evaluation through the expression.
   * May be sparse.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
   */
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <pre>
   * An ordered list of results.
   * Tracks the flow of evaluation through the expression.
   * May be sparse.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
   */
  public com.google.api.expr.v1beta1.EvalState.Result getResults(int index) {
    return results_.get(index);
  }
  /**
   * <pre>
   * An ordered list of results.
   * Tracks the flow of evaluation through the expression.
   * May be sparse.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
   */
  public com.google.api.expr.v1beta1.EvalState.ResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < values_.size(); i++) {
      output.writeMessage(1, values_.get(i));
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(3, results_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < values_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, values_.get(i));
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, results_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.api.expr.v1beta1.EvalState)) {
      return super.equals(obj);
    }
    com.google.api.expr.v1beta1.EvalState other = (com.google.api.expr.v1beta1.EvalState) obj;

    boolean result = true;
    result = result && getValuesList()
        .equals(other.getValuesList());
    result = result && getResultsList()
        .equals(other.getResultsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.EvalState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.EvalState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.EvalState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.expr.v1beta1.EvalState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The state of an evaluation.
   * Can represent an initial, partial, or completed state of evaluation.
   * </pre>
   *
   * Protobuf type {@code google.api.expr.v1beta1.EvalState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.expr.v1beta1.EvalState)
      com.google.api.expr.v1beta1.EvalStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.api.expr.v1beta1.EvalState.class, com.google.api.expr.v1beta1.EvalState.Builder.class);
    }

    // Construct using com.google.api.expr.v1beta1.EvalState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValuesFieldBuilder();
        getResultsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        valuesBuilder_.clear();
      }
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_EvalState_descriptor;
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.EvalState getDefaultInstanceForType() {
      return com.google.api.expr.v1beta1.EvalState.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.EvalState build() {
      com.google.api.expr.v1beta1.EvalState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.EvalState buildPartial() {
      com.google.api.expr.v1beta1.EvalState result = new com.google.api.expr.v1beta1.EvalState(this);
      int from_bitField0_ = bitField0_;
      if (valuesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
      } else {
        result.values_ = valuesBuilder_.build();
      }
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.api.expr.v1beta1.EvalState) {
        return mergeFrom((com.google.api.expr.v1beta1.EvalState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.api.expr.v1beta1.EvalState other) {
      if (other == com.google.api.expr.v1beta1.EvalState.getDefaultInstance()) return this;
      if (valuesBuilder_ == null) {
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
      } else {
        if (!other.values_.isEmpty()) {
          if (valuesBuilder_.isEmpty()) {
            valuesBuilder_.dispose();
            valuesBuilder_ = null;
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
            valuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesFieldBuilder() : null;
          } else {
            valuesBuilder_.addAllMessages(other.values_);
          }
        }
      }
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000002);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.api.expr.v1beta1.EvalState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.api.expr.v1beta1.EvalState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.api.expr.v1beta1.ExprValue> values_ =
      java.util.Collections.emptyList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        values_ = new java.util.ArrayList<com.google.api.expr.v1beta1.ExprValue>(values_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.ExprValue, com.google.api.expr.v1beta1.ExprValue.Builder, com.google.api.expr.v1beta1.ExprValueOrBuilder> valuesBuilder_;

    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.ExprValue> getValuesList() {
      if (valuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(values_);
      } else {
        return valuesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public int getValuesCount() {
      if (valuesBuilder_ == null) {
        return values_.size();
      } else {
        return valuesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public com.google.api.expr.v1beta1.ExprValue getValues(int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);
      } else {
        return valuesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder setValues(
        int index, com.google.api.expr.v1beta1.ExprValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder setValues(
        int index, com.google.api.expr.v1beta1.ExprValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder addValues(com.google.api.expr.v1beta1.ExprValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder addValues(
        int index, com.google.api.expr.v1beta1.ExprValue value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder addValues(
        com.google.api.expr.v1beta1.ExprValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder addValues(
        int index, com.google.api.expr.v1beta1.ExprValue.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends com.google.api.expr.v1beta1.ExprValue> values) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
      } else {
        valuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder clearValues() {
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public Builder removeValues(int index) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.remove(index);
        onChanged();
      } else {
        valuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public com.google.api.expr.v1beta1.ExprValue.Builder getValuesBuilder(
        int index) {
      return getValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public com.google.api.expr.v1beta1.ExprValueOrBuilder getValuesOrBuilder(
        int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);  } else {
        return valuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public java.util.List<? extends com.google.api.expr.v1beta1.ExprValueOrBuilder> 
         getValuesOrBuilderList() {
      if (valuesBuilder_ != null) {
        return valuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(values_);
      }
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public com.google.api.expr.v1beta1.ExprValue.Builder addValuesBuilder() {
      return getValuesFieldBuilder().addBuilder(
          com.google.api.expr.v1beta1.ExprValue.getDefaultInstance());
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public com.google.api.expr.v1beta1.ExprValue.Builder addValuesBuilder(
        int index) {
      return getValuesFieldBuilder().addBuilder(
          index, com.google.api.expr.v1beta1.ExprValue.getDefaultInstance());
    }
    /**
     * <pre>
     * The unique values referenced in this message.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.ExprValue.Builder> 
         getValuesBuilderList() {
      return getValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.ExprValue, com.google.api.expr.v1beta1.ExprValue.Builder, com.google.api.expr.v1beta1.ExprValueOrBuilder> 
        getValuesFieldBuilder() {
      if (valuesBuilder_ == null) {
        valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.api.expr.v1beta1.ExprValue, com.google.api.expr.v1beta1.ExprValue.Builder, com.google.api.expr.v1beta1.ExprValueOrBuilder>(
                values_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      return valuesBuilder_;
    }

    private java.util.List<com.google.api.expr.v1beta1.EvalState.Result> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        results_ = new java.util.ArrayList<com.google.api.expr.v1beta1.EvalState.Result>(results_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.EvalState.Result, com.google.api.expr.v1beta1.EvalState.Result.Builder, com.google.api.expr.v1beta1.EvalState.ResultOrBuilder> resultsBuilder_;

    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.EvalState.Result> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public com.google.api.expr.v1beta1.EvalState.Result getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder setResults(
        int index, com.google.api.expr.v1beta1.EvalState.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder setResults(
        int index, com.google.api.expr.v1beta1.EvalState.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder addResults(com.google.api.expr.v1beta1.EvalState.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder addResults(
        int index, com.google.api.expr.v1beta1.EvalState.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder addResults(
        com.google.api.expr.v1beta1.EvalState.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder addResults(
        int index, com.google.api.expr.v1beta1.EvalState.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.google.api.expr.v1beta1.EvalState.Result> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public com.google.api.expr.v1beta1.EvalState.Result.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public com.google.api.expr.v1beta1.EvalState.ResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public java.util.List<? extends com.google.api.expr.v1beta1.EvalState.ResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public com.google.api.expr.v1beta1.EvalState.Result.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          com.google.api.expr.v1beta1.EvalState.Result.getDefaultInstance());
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public com.google.api.expr.v1beta1.EvalState.Result.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, com.google.api.expr.v1beta1.EvalState.Result.getDefaultInstance());
    }
    /**
     * <pre>
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.EvalState.Result.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.EvalState.Result, com.google.api.expr.v1beta1.EvalState.Result.Builder, com.google.api.expr.v1beta1.EvalState.ResultOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.api.expr.v1beta1.EvalState.Result, com.google.api.expr.v1beta1.EvalState.Result.Builder, com.google.api.expr.v1beta1.EvalState.ResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.api.expr.v1beta1.EvalState)
  }

  // @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.EvalState)
  private static final com.google.api.expr.v1beta1.EvalState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.api.expr.v1beta1.EvalState();
  }

  public static com.google.api.expr.v1beta1.EvalState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvalState>
      PARSER = new com.google.protobuf.AbstractParser<EvalState>() {
    @java.lang.Override
    public EvalState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EvalState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EvalState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EvalState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.api.expr.v1beta1.EvalState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

