// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1beta1/expr.proto

package com.google.api.expr.v1beta1;

public interface ExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.api.expr.v1beta1.Expr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. An id assigned to this node by the parser which is unique in a
   * given expression tree. This is used to associate type information and other
   * attributes to a node in the parse tree.
   * </pre>
   *
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <pre>
   * A literal expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Literal literal_expr = 3;</code>
   */
  boolean hasLiteralExpr();
  /**
   * <pre>
   * A literal expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Literal literal_expr = 3;</code>
   */
  com.google.api.expr.v1beta1.Literal getLiteralExpr();
  /**
   * <pre>
   * A literal expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Literal literal_expr = 3;</code>
   */
  com.google.api.expr.v1beta1.LiteralOrBuilder getLiteralExprOrBuilder();

  /**
   * <pre>
   * An identifier expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Ident ident_expr = 4;</code>
   */
  boolean hasIdentExpr();
  /**
   * <pre>
   * An identifier expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Ident ident_expr = 4;</code>
   */
  com.google.api.expr.v1beta1.Expr.Ident getIdentExpr();
  /**
   * <pre>
   * An identifier expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Ident ident_expr = 4;</code>
   */
  com.google.api.expr.v1beta1.Expr.IdentOrBuilder getIdentExprOrBuilder();

  /**
   * <pre>
   * A field selection expression, e.g. `request.auth`.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Select select_expr = 5;</code>
   */
  boolean hasSelectExpr();
  /**
   * <pre>
   * A field selection expression, e.g. `request.auth`.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Select select_expr = 5;</code>
   */
  com.google.api.expr.v1beta1.Expr.Select getSelectExpr();
  /**
   * <pre>
   * A field selection expression, e.g. `request.auth`.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Select select_expr = 5;</code>
   */
  com.google.api.expr.v1beta1.Expr.SelectOrBuilder getSelectExprOrBuilder();

  /**
   * <pre>
   * A call expression, including calls to predefined functions and operators.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Call call_expr = 6;</code>
   */
  boolean hasCallExpr();
  /**
   * <pre>
   * A call expression, including calls to predefined functions and operators.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Call call_expr = 6;</code>
   */
  com.google.api.expr.v1beta1.Expr.Call getCallExpr();
  /**
   * <pre>
   * A call expression, including calls to predefined functions and operators.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Call call_expr = 6;</code>
   */
  com.google.api.expr.v1beta1.Expr.CallOrBuilder getCallExprOrBuilder();

  /**
   * <pre>
   * A list creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateList list_expr = 7;</code>
   */
  boolean hasListExpr();
  /**
   * <pre>
   * A list creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateList list_expr = 7;</code>
   */
  com.google.api.expr.v1beta1.Expr.CreateList getListExpr();
  /**
   * <pre>
   * A list creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateList list_expr = 7;</code>
   */
  com.google.api.expr.v1beta1.Expr.CreateListOrBuilder getListExprOrBuilder();

  /**
   * <pre>
   * A map or object creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateStruct struct_expr = 8;</code>
   */
  boolean hasStructExpr();
  /**
   * <pre>
   * A map or object creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateStruct struct_expr = 8;</code>
   */
  com.google.api.expr.v1beta1.Expr.CreateStruct getStructExpr();
  /**
   * <pre>
   * A map or object creation expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.CreateStruct struct_expr = 8;</code>
   */
  com.google.api.expr.v1beta1.Expr.CreateStructOrBuilder getStructExprOrBuilder();

  /**
   * <pre>
   * A comprehension expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Comprehension comprehension_expr = 9;</code>
   */
  boolean hasComprehensionExpr();
  /**
   * <pre>
   * A comprehension expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Comprehension comprehension_expr = 9;</code>
   */
  com.google.api.expr.v1beta1.Expr.Comprehension getComprehensionExpr();
  /**
   * <pre>
   * A comprehension expression.
   * </pre>
   *
   * <code>.google.api.expr.v1beta1.Expr.Comprehension comprehension_expr = 9;</code>
   */
  com.google.api.expr.v1beta1.Expr.ComprehensionOrBuilder getComprehensionExprOrBuilder();

  public com.google.api.expr.v1beta1.Expr.ExprKindCase getExprKindCase();
}
