// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1beta1/eval.proto

package com.google.api.expr.v1beta1;

/**
 * <pre>
 * A set of expressions for which the value is unknown.
 * The unknowns included depend on the context. See `ExprValue.unknown`.
 * </pre>
 *
 * Protobuf type {@code google.api.expr.v1beta1.UnknownSet}
 */
public  final class UnknownSet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.api.expr.v1beta1.UnknownSet)
    UnknownSetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnknownSet.newBuilder() to construct.
  private UnknownSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnknownSet() {
    exprs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnknownSet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              exprs_ = new java.util.ArrayList<com.google.api.expr.v1beta1.IdRef>();
              mutable_bitField0_ |= 0x00000001;
            }
            exprs_.add(
                input.readMessage(com.google.api.expr.v1beta1.IdRef.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        exprs_ = java.util.Collections.unmodifiableList(exprs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_UnknownSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_UnknownSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.api.expr.v1beta1.UnknownSet.class, com.google.api.expr.v1beta1.UnknownSet.Builder.class);
  }

  public static final int EXPRS_FIELD_NUMBER = 1;
  private java.util.List<com.google.api.expr.v1beta1.IdRef> exprs_;
  /**
   * <pre>
   * The ids of the expressions with unknown values.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
   */
  public java.util.List<com.google.api.expr.v1beta1.IdRef> getExprsList() {
    return exprs_;
  }
  /**
   * <pre>
   * The ids of the expressions with unknown values.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
   */
  public java.util.List<? extends com.google.api.expr.v1beta1.IdRefOrBuilder> 
      getExprsOrBuilderList() {
    return exprs_;
  }
  /**
   * <pre>
   * The ids of the expressions with unknown values.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
   */
  public int getExprsCount() {
    return exprs_.size();
  }
  /**
   * <pre>
   * The ids of the expressions with unknown values.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
   */
  public com.google.api.expr.v1beta1.IdRef getExprs(int index) {
    return exprs_.get(index);
  }
  /**
   * <pre>
   * The ids of the expressions with unknown values.
   * </pre>
   *
   * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
   */
  public com.google.api.expr.v1beta1.IdRefOrBuilder getExprsOrBuilder(
      int index) {
    return exprs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < exprs_.size(); i++) {
      output.writeMessage(1, exprs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < exprs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, exprs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.api.expr.v1beta1.UnknownSet)) {
      return super.equals(obj);
    }
    com.google.api.expr.v1beta1.UnknownSet other = (com.google.api.expr.v1beta1.UnknownSet) obj;

    boolean result = true;
    result = result && getExprsList()
        .equals(other.getExprsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getExprsCount() > 0) {
      hash = (37 * hash) + EXPRS_FIELD_NUMBER;
      hash = (53 * hash) + getExprsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.api.expr.v1beta1.UnknownSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.api.expr.v1beta1.UnknownSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A set of expressions for which the value is unknown.
   * The unknowns included depend on the context. See `ExprValue.unknown`.
   * </pre>
   *
   * Protobuf type {@code google.api.expr.v1beta1.UnknownSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.api.expr.v1beta1.UnknownSet)
      com.google.api.expr.v1beta1.UnknownSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_UnknownSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_UnknownSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.api.expr.v1beta1.UnknownSet.class, com.google.api.expr.v1beta1.UnknownSet.Builder.class);
    }

    // Construct using com.google.api.expr.v1beta1.UnknownSet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExprsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (exprsBuilder_ == null) {
        exprs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        exprsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.api.expr.v1beta1.EvalProto.internal_static_google_api_expr_v1beta1_UnknownSet_descriptor;
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.UnknownSet getDefaultInstanceForType() {
      return com.google.api.expr.v1beta1.UnknownSet.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.UnknownSet build() {
      com.google.api.expr.v1beta1.UnknownSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.api.expr.v1beta1.UnknownSet buildPartial() {
      com.google.api.expr.v1beta1.UnknownSet result = new com.google.api.expr.v1beta1.UnknownSet(this);
      int from_bitField0_ = bitField0_;
      if (exprsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          exprs_ = java.util.Collections.unmodifiableList(exprs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.exprs_ = exprs_;
      } else {
        result.exprs_ = exprsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.api.expr.v1beta1.UnknownSet) {
        return mergeFrom((com.google.api.expr.v1beta1.UnknownSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.api.expr.v1beta1.UnknownSet other) {
      if (other == com.google.api.expr.v1beta1.UnknownSet.getDefaultInstance()) return this;
      if (exprsBuilder_ == null) {
        if (!other.exprs_.isEmpty()) {
          if (exprs_.isEmpty()) {
            exprs_ = other.exprs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExprsIsMutable();
            exprs_.addAll(other.exprs_);
          }
          onChanged();
        }
      } else {
        if (!other.exprs_.isEmpty()) {
          if (exprsBuilder_.isEmpty()) {
            exprsBuilder_.dispose();
            exprsBuilder_ = null;
            exprs_ = other.exprs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            exprsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExprsFieldBuilder() : null;
          } else {
            exprsBuilder_.addAllMessages(other.exprs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.api.expr.v1beta1.UnknownSet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.api.expr.v1beta1.UnknownSet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.api.expr.v1beta1.IdRef> exprs_ =
      java.util.Collections.emptyList();
    private void ensureExprsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        exprs_ = new java.util.ArrayList<com.google.api.expr.v1beta1.IdRef>(exprs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder> exprsBuilder_;

    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.IdRef> getExprsList() {
      if (exprsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exprs_);
      } else {
        return exprsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public int getExprsCount() {
      if (exprsBuilder_ == null) {
        return exprs_.size();
      } else {
        return exprsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRef getExprs(int index) {
      if (exprsBuilder_ == null) {
        return exprs_.get(index);
      } else {
        return exprsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder setExprs(
        int index, com.google.api.expr.v1beta1.IdRef value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.set(index, value);
        onChanged();
      } else {
        exprsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder setExprs(
        int index, com.google.api.expr.v1beta1.IdRef.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.set(index, builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder addExprs(com.google.api.expr.v1beta1.IdRef value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.add(value);
        onChanged();
      } else {
        exprsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder addExprs(
        int index, com.google.api.expr.v1beta1.IdRef value) {
      if (exprsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExprsIsMutable();
        exprs_.add(index, value);
        onChanged();
      } else {
        exprsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder addExprs(
        com.google.api.expr.v1beta1.IdRef.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.add(builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder addExprs(
        int index, com.google.api.expr.v1beta1.IdRef.Builder builderForValue) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.add(index, builderForValue.build());
        onChanged();
      } else {
        exprsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder addAllExprs(
        java.lang.Iterable<? extends com.google.api.expr.v1beta1.IdRef> values) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exprs_);
        onChanged();
      } else {
        exprsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder clearExprs() {
      if (exprsBuilder_ == null) {
        exprs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        exprsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public Builder removeExprs(int index) {
      if (exprsBuilder_ == null) {
        ensureExprsIsMutable();
        exprs_.remove(index);
        onChanged();
      } else {
        exprsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRef.Builder getExprsBuilder(
        int index) {
      return getExprsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRefOrBuilder getExprsOrBuilder(
        int index) {
      if (exprsBuilder_ == null) {
        return exprs_.get(index);  } else {
        return exprsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public java.util.List<? extends com.google.api.expr.v1beta1.IdRefOrBuilder> 
         getExprsOrBuilderList() {
      if (exprsBuilder_ != null) {
        return exprsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exprs_);
      }
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRef.Builder addExprsBuilder() {
      return getExprsFieldBuilder().addBuilder(
          com.google.api.expr.v1beta1.IdRef.getDefaultInstance());
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public com.google.api.expr.v1beta1.IdRef.Builder addExprsBuilder(
        int index) {
      return getExprsFieldBuilder().addBuilder(
          index, com.google.api.expr.v1beta1.IdRef.getDefaultInstance());
    }
    /**
     * <pre>
     * The ids of the expressions with unknown values.
     * </pre>
     *
     * <code>repeated .google.api.expr.v1beta1.IdRef exprs = 1;</code>
     */
    public java.util.List<com.google.api.expr.v1beta1.IdRef.Builder> 
         getExprsBuilderList() {
      return getExprsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder> 
        getExprsFieldBuilder() {
      if (exprsBuilder_ == null) {
        exprsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.api.expr.v1beta1.IdRef, com.google.api.expr.v1beta1.IdRef.Builder, com.google.api.expr.v1beta1.IdRefOrBuilder>(
                exprs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        exprs_ = null;
      }
      return exprsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.api.expr.v1beta1.UnknownSet)
  }

  // @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.UnknownSet)
  private static final com.google.api.expr.v1beta1.UnknownSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.api.expr.v1beta1.UnknownSet();
  }

  public static com.google.api.expr.v1beta1.UnknownSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnknownSet>
      PARSER = new com.google.protobuf.AbstractParser<UnknownSet>() {
    @java.lang.Override
    public UnknownSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnknownSet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnknownSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnknownSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.api.expr.v1beta1.UnknownSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

