// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/v1beta3/entity.proto

package com.google.datastore.v1beta3;

public interface ArrayValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1beta3.ArrayValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Values in the array.
   * The order of this array may not be preserved if it contains a mix of
   * indexed and unindexed values.
   * </pre>
   *
   * <code>repeated .google.datastore.v1beta3.Value values = 1;</code>
   */
  java.util.List<com.google.datastore.v1beta3.Value> 
      getValuesList();
  /**
   * <pre>
   * Values in the array.
   * The order of this array may not be preserved if it contains a mix of
   * indexed and unindexed values.
   * </pre>
   *
   * <code>repeated .google.datastore.v1beta3.Value values = 1;</code>
   */
  com.google.datastore.v1beta3.Value getValues(int index);
  /**
   * <pre>
   * Values in the array.
   * The order of this array may not be preserved if it contains a mix of
   * indexed and unindexed values.
   * </pre>
   *
   * <code>repeated .google.datastore.v1beta3.Value values = 1;</code>
   */
  int getValuesCount();
  /**
   * <pre>
   * Values in the array.
   * The order of this array may not be preserved if it contains a mix of
   * indexed and unindexed values.
   * </pre>
   *
   * <code>repeated .google.datastore.v1beta3.Value values = 1;</code>
   */
  java.util.List<? extends com.google.datastore.v1beta3.ValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <pre>
   * Values in the array.
   * The order of this array may not be preserved if it contains a mix of
   * indexed and unindexed values.
   * </pre>
   *
   * <code>repeated .google.datastore.v1beta3.Value values = 1;</code>
   */
  com.google.datastore.v1beta3.ValueOrBuilder getValuesOrBuilder(
      int index);
}
