// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/v1beta3/query.proto

package com.google.datastore.v1beta3;

public final class QueryProto {
  private QueryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_EntityResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_EntityResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_Query_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_Query_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_KindExpression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_KindExpression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_PropertyReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_PropertyReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_Projection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_Projection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_PropertyOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_PropertyOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_Filter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_CompositeFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_CompositeFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_PropertyFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_PropertyFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_GqlQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_GqlQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_GqlQuery_NamedBindingsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_GqlQuery_NamedBindingsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_GqlQueryParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_GqlQueryParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_datastore_v1beta3_QueryResultBatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_v1beta3_QueryResultBatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$google/datastore/v1beta3/query.proto\022\030" +
      "google.datastore.v1beta3\032\034google/api/ann" +
      "otations.proto\032%google/datastore/v1beta3" +
      "/entity.proto\032\036google/protobuf/wrappers." +
      "proto\032\030google/type/latlng.proto\"\264\001\n\014Enti" +
      "tyResult\0220\n\006entity\030\001 \001(\0132 .google.datast" +
      "ore.v1beta3.Entity\022\017\n\007version\030\004 \001(\003\022\016\n\006c" +
      "ursor\030\003 \001(\014\"Q\n\nResultType\022\033\n\027RESULT_TYPE" +
      "_UNSPECIFIED\020\000\022\010\n\004FULL\020\001\022\016\n\nPROJECTION\020\002" +
      "\022\014\n\010KEY_ONLY\020\003\"\213\003\n\005Query\0228\n\nprojection\030\002" +
      " \003(\0132$.google.datastore.v1beta3.Projecti" +
      "on\0226\n\004kind\030\003 \003(\0132(.google.datastore.v1be" +
      "ta3.KindExpression\0220\n\006filter\030\004 \001(\0132 .goo" +
      "gle.datastore.v1beta3.Filter\0226\n\005order\030\005 " +
      "\003(\0132\'.google.datastore.v1beta3.PropertyO" +
      "rder\022@\n\013distinct_on\030\006 \003(\0132+.google.datas" +
      "tore.v1beta3.PropertyReference\022\024\n\014start_" +
      "cursor\030\007 \001(\014\022\022\n\nend_cursor\030\010 \001(\014\022\016\n\006offs" +
      "et\030\n \001(\005\022*\n\005limit\030\014 \001(\0132\033.google.protobu" +
      "f.Int32Value\"\036\n\016KindExpression\022\014\n\004name\030\001" +
      " \001(\t\"!\n\021PropertyReference\022\014\n\004name\030\002 \001(\t\"" +
      "K\n\nProjection\022=\n\010property\030\001 \001(\0132+.google" +
      ".datastore.v1beta3.PropertyReference\"\333\001\n" +
      "\rPropertyOrder\022=\n\010property\030\001 \001(\0132+.googl" +
      "e.datastore.v1beta3.PropertyReference\022D\n" +
      "\tdirection\030\002 \001(\01621.google.datastore.v1be" +
      "ta3.PropertyOrder.Direction\"E\n\tDirection" +
      "\022\031\n\025DIRECTION_UNSPECIFIED\020\000\022\r\n\tASCENDING" +
      "\020\001\022\016\n\nDESCENDING\020\002\"\243\001\n\006Filter\022E\n\020composi" +
      "te_filter\030\001 \001(\0132).google.datastore.v1bet" +
      "a3.CompositeFilterH\000\022C\n\017property_filter\030" +
      "\002 \001(\0132(.google.datastore.v1beta3.Propert" +
      "yFilterH\000B\r\n\013filter_type\"\263\001\n\017CompositeFi" +
      "lter\022>\n\002op\030\001 \001(\01622.google.datastore.v1be" +
      "ta3.CompositeFilter.Operator\0221\n\007filters\030" +
      "\002 \003(\0132 .google.datastore.v1beta3.Filter\"" +
      "-\n\010Operator\022\030\n\024OPERATOR_UNSPECIFIED\020\000\022\007\n" +
      "\003AND\020\001\"\326\002\n\016PropertyFilter\022=\n\010property\030\001 " +
      "\001(\0132+.google.datastore.v1beta3.PropertyR" +
      "eference\022=\n\002op\030\002 \001(\01621.google.datastore." +
      "v1beta3.PropertyFilter.Operator\022.\n\005value" +
      "\030\003 \001(\0132\037.google.datastore.v1beta3.Value\"" +
      "\225\001\n\010Operator\022\030\n\024OPERATOR_UNSPECIFIED\020\000\022\r" +
      "\n\tLESS_THAN\020\001\022\026\n\022LESS_THAN_OR_EQUAL\020\002\022\020\n" +
      "\014GREATER_THAN\020\003\022\031\n\025GREATER_THAN_OR_EQUAL" +
      "\020\004\022\t\n\005EQUAL\020\005\022\020\n\014HAS_ANCESTOR\020\013\"\264\002\n\010GqlQ" +
      "uery\022\024\n\014query_string\030\001 \001(\t\022\026\n\016allow_lite" +
      "rals\030\002 \001(\010\022M\n\016named_bindings\030\005 \003(\01325.goo" +
      "gle.datastore.v1beta3.GqlQuery.NamedBind" +
      "ingsEntry\022H\n\023positional_bindings\030\004 \003(\0132+" +
      ".google.datastore.v1beta3.GqlQueryParame" +
      "ter\032a\n\022NamedBindingsEntry\022\013\n\003key\030\001 \001(\t\022:" +
      "\n\005value\030\002 \001(\0132+.google.datastore.v1beta3" +
      ".GqlQueryParameter:\0028\001\"i\n\021GqlQueryParame" +
      "ter\0220\n\005value\030\002 \001(\0132\037.google.datastore.v1" +
      "beta3.ValueH\000\022\020\n\006cursor\030\003 \001(\014H\000B\020\n\016param" +
      "eter_type\"\355\003\n\020QueryResultBatch\022\027\n\017skippe" +
      "d_results\030\006 \001(\005\022\026\n\016skipped_cursor\030\003 \001(\014\022" +
      "M\n\022entity_result_type\030\001 \001(\01621.google.dat" +
      "astore.v1beta3.EntityResult.ResultType\022>" +
      "\n\016entity_results\030\002 \003(\0132&.google.datastor" +
      "e.v1beta3.EntityResult\022\022\n\nend_cursor\030\004 \001" +
      "(\014\022P\n\014more_results\030\005 \001(\0162:.google.datast" +
      "ore.v1beta3.QueryResultBatch.MoreResults" +
      "Type\022\030\n\020snapshot_version\030\007 \001(\003\"\230\001\n\017MoreR" +
      "esultsType\022!\n\035MORE_RESULTS_TYPE_UNSPECIF" +
      "IED\020\000\022\020\n\014NOT_FINISHED\020\001\022\034\n\030MORE_RESULTS_" +
      "AFTER_LIMIT\020\002\022\035\n\031MORE_RESULTS_AFTER_CURS" +
      "OR\020\004\022\023\n\017NO_MORE_RESULTS\020\003B\261\001\n\034com.google" +
      ".datastore.v1beta3B\nQueryProtoP\001ZAgoogle" +
      ".golang.org/genproto/googleapis/datastor" +
      "e/v1beta3;datastore\252\002\036Google.Cloud.Datas" +
      "tore.V1Beta3\312\002\036Google\\Cloud\\Datastore\\V1" +
      "beta3b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.datastore.v1beta3.EntityProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.type.LatLngProto.getDescriptor(),
        }, assigner);
    internal_static_google_datastore_v1beta3_EntityResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_datastore_v1beta3_EntityResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_EntityResult_descriptor,
        new java.lang.String[] { "Entity", "Version", "Cursor", });
    internal_static_google_datastore_v1beta3_Query_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_datastore_v1beta3_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_Query_descriptor,
        new java.lang.String[] { "Projection", "Kind", "Filter", "Order", "DistinctOn", "StartCursor", "EndCursor", "Offset", "Limit", });
    internal_static_google_datastore_v1beta3_KindExpression_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_datastore_v1beta3_KindExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_KindExpression_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_datastore_v1beta3_PropertyReference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_datastore_v1beta3_PropertyReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_PropertyReference_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_datastore_v1beta3_Projection_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_datastore_v1beta3_Projection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_Projection_descriptor,
        new java.lang.String[] { "Property", });
    internal_static_google_datastore_v1beta3_PropertyOrder_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_datastore_v1beta3_PropertyOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_PropertyOrder_descriptor,
        new java.lang.String[] { "Property", "Direction", });
    internal_static_google_datastore_v1beta3_Filter_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_datastore_v1beta3_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_Filter_descriptor,
        new java.lang.String[] { "CompositeFilter", "PropertyFilter", "FilterType", });
    internal_static_google_datastore_v1beta3_CompositeFilter_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_datastore_v1beta3_CompositeFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_CompositeFilter_descriptor,
        new java.lang.String[] { "Op", "Filters", });
    internal_static_google_datastore_v1beta3_PropertyFilter_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_datastore_v1beta3_PropertyFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_PropertyFilter_descriptor,
        new java.lang.String[] { "Property", "Op", "Value", });
    internal_static_google_datastore_v1beta3_GqlQuery_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_datastore_v1beta3_GqlQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_GqlQuery_descriptor,
        new java.lang.String[] { "QueryString", "AllowLiterals", "NamedBindings", "PositionalBindings", });
    internal_static_google_datastore_v1beta3_GqlQuery_NamedBindingsEntry_descriptor =
      internal_static_google_datastore_v1beta3_GqlQuery_descriptor.getNestedTypes().get(0);
    internal_static_google_datastore_v1beta3_GqlQuery_NamedBindingsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_GqlQuery_NamedBindingsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_datastore_v1beta3_GqlQueryParameter_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_datastore_v1beta3_GqlQueryParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_GqlQueryParameter_descriptor,
        new java.lang.String[] { "Value", "Cursor", "ParameterType", });
    internal_static_google_datastore_v1beta3_QueryResultBatch_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_datastore_v1beta3_QueryResultBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_datastore_v1beta3_QueryResultBatch_descriptor,
        new java.lang.String[] { "SkippedResults", "SkippedCursor", "EntityResultType", "EntityResults", "EndCursor", "MoreResults", "SnapshotVersion", });
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.datastore.v1beta3.EntityProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.type.LatLngProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
