// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/v1beta3/datastore.proto

package com.google.datastore.v1beta3;

public interface RunQueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1beta3.RunQueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A batch of query results (always present).
   * </pre>
   *
   * <code>.google.datastore.v1beta3.QueryResultBatch batch = 1;</code>
   */
  boolean hasBatch();
  /**
   * <pre>
   * A batch of query results (always present).
   * </pre>
   *
   * <code>.google.datastore.v1beta3.QueryResultBatch batch = 1;</code>
   */
  com.google.datastore.v1beta3.QueryResultBatch getBatch();
  /**
   * <pre>
   * A batch of query results (always present).
   * </pre>
   *
   * <code>.google.datastore.v1beta3.QueryResultBatch batch = 1;</code>
   */
  com.google.datastore.v1beta3.QueryResultBatchOrBuilder getBatchOrBuilder();

  /**
   * <pre>
   * The parsed form of the `GqlQuery` from the request, if it was set.
   * </pre>
   *
   * <code>.google.datastore.v1beta3.Query query = 2;</code>
   */
  boolean hasQuery();
  /**
   * <pre>
   * The parsed form of the `GqlQuery` from the request, if it was set.
   * </pre>
   *
   * <code>.google.datastore.v1beta3.Query query = 2;</code>
   */
  com.google.datastore.v1beta3.Query getQuery();
  /**
   * <pre>
   * The parsed form of the `GqlQuery` from the request, if it was set.
   * </pre>
   *
   * <code>.google.datastore.v1beta3.Query query = 2;</code>
   */
  com.google.datastore.v1beta3.QueryOrBuilder getQueryOrBuilder();
}
